### ISSUE TITLE
Приложение и соединение зависают после смены языка ОС

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardVPNForMac#103]
Здравствуйте,

приложение _и соединение_ начали зависать после смены языка системы. Как при работе через строку меню, так и при открытии интерфейса и попытке изменения подключения:

![2022-04-20_11-31-16](https://user-images.githubusercontent.com/45385632/164189205-89cb3223-d6b4-4178-967f-3d84f2280191.png)

В приложении логи, которые мне удалось выгрузить после отвала соединения, но перед зависанием GUI:
[adguard_logs_20220420084552.zip](https://github.com/AdguardTeam/AdGuardVPNForMac/files/8519874/adguard_logs_20220420084552.zip)

Тут логи после принудительного перезапуска:
[adguard_logs_20220420084851.zip](https://github.com/AdguardTeam/AdGuardVPNForMac/files/8519875/adguard_logs_20220420084851.zip)

Версия приложения 1.2.2.198, версия ОС 12.3.1.

Спасибо.

**Comment by ammnt** [comment]
Вот тут уже поинтереснее. Если в списке исключений добавлен домен и IP для него, то приложение не зависает. Если только домен, то приложение зависает и отваливается резолвинг полностью (через приложение-блокировщик):
![image](https://user-images.githubusercontent.com/45385632/164317831-fc18c71d-e36b-4331-a5c2-db811faef9bf.png)

Связано с https://github.com/AdguardTeam/VpnLibs/issues/19 и https://github.com/AdguardTeam/AdGuardVPNForMac/issues/104

**Comment by maxikuzmin** [comment]
Спасибо! Мы в курсе о данной проблеме, планируем исправить это в ближайших обновлениях
