### ISSUE TITLE
mosenergosbyt.ru не работает после добавления в исключения

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardVPNForMac#104]
Здравствуйте,

mosenergosbyt.ru и my.mosenergosbyt.ru не работают после добавления в исключения. Только при полном отключении соединения. Расширенные логи в приложении. Версия приложения 1.2.2.198, версия ОС 12.3.1.

Спасибо.

**Comment by sfionov** [comment]
Добрый день!

К сожалению, не удаётся повторить.

Повторяется ли проблема, если список исключений состоит только из данных доменов?

Кроме того, зачастую для посещения государственных сайтов в России необходимо так же добавлять в исключения third-party ресурсы. Например, данный сайт обращается к pay.vbrr.ru.

**Comment by sfionov** [comment]
Добрый день!

К сожалению, не удаётся повторить.

Повторяется ли проблема, если список исключений состоит только из данных доменов?

Кроме того, зачастую для посещения государственных сайтов в России необходимо так же добавлять в исключения third-party ресурсы. Например, данный сайт обращается к pay.vbrr.ru.

**Comment by ammnt** [comment]
@sfionov, это была эта проблема:
https://github.com/AdguardTeam/VpnLibs/issues/19

Можете закрыть этот тикет.

**Comment by maxikuzmin** [comment]
Duplicate https://github.com/AdguardTeam/VpnLibs/issues/19
