### ISSUE TITLE
Add diagnostic info like android version

### ISSUE THREAD

**Issue by aliafshany** [AdguardTeam/AdGuardVPNForMac#106]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

I wish the mac version had a diagnostic information function like the android version.

best

![image](https://user-images.githubusercontent.com/40741745/169291828-77346a4d-d93d-4294-b359-e933b576f697.png)
![image](https://user-images.githubusercontent.com/40741745/169292182-c9c01748-8191-4d43-8b58-e474f0c5415d.png)

**Comment by harry-b** [comment]
Hi @alysha. There is state.txt file in the log archive which includes this information. Moreover we have added more such information in VPN v2.0. It will be released soon.

**Comment by aliafshany** [comment]
I really appreciate it.
