### ISSUE TITLE
stacksocial.com 403 error on berlin location

### ISSUE THREAD

**Issue by aliafshany** [AdguardTeam/AdGuardVPNForMac#108]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard VPN version:**
  -  Version 1.2.3.204 nightly
- **VPN mode:**
  -  Local VPN
- **Operating system and version:**
  -  mac os 11.6.2
- **Other network-level software:**
  -  Adguard ad-blocker

### Expected Behavior

  403 Forbidden error on Berlin location.
it's not on frankfurt btw

### Actual Behavior

 403 Forbidden error

### Screenshots

 

![image](https://user-images.githubusercontent.com/40741745/169301790-919cb370-471a-498f-976c-8d9dbe60a695.png)

</details>

### Additional Information

Logs:
[adguard_logs_20220519011131.zip](https://github.com/AdguardTeam/AdGuardVPNForMac/files/8729395/adguard_logs_20220519011131.zip)

**Comment by Chinaski1** [comment]
Hi there!

The point is that the IP address of the location was probably banned on the domain side.  We change locations from time to time to avoid this situation. Unfortunately, there is nothing we can do to solve this problem immediately.
