### ISSUE TITLE
Can't remove AdGuard VPN for macOS from AdGuard Account, or rename device properly

### ISSUE THREAD

**Issue by gGkAC3qfszbdViFkw4Fk9ooS2u** [AdguardTeam/AdGuardVPNForMac#110]
### Issue Details

- **AdGuard VPN version:**
  - AdGuard VPN is not installed.
- **VPN mode:**
  - NA
- **Operating system and version:**
  - NA
- **Other network-level software:**
  - AdGuard Ad Blocker

### Expected Behavior

A way to remove AdGuard VPN from my AdGuard account.

### Actual Behavior

There is no way for me to remove AdGuard VPN from my AdGuard account.

### Screenshots

<img width="1189" alt="Screen Shot 2022-05-24 at 1 20 29 pm" src="https://user-images.githubusercontent.com/95468948/169942497-4aaf56af-6b06-45b5-a99d-9b3144f49ad6.png">

### Additional Information

In the above image you'll see Test device and Test device 3.
If I tap on Test device to rename it, it will show Test device 3. If I try to rename it to Test device 2, it will rename Test device 3, to Test device 2, leaving Test device as is.

https://user-images.githubusercontent.com/95468948/169942940-8e095774-3574-4fc1-bb4b-82c2f0e994ef.mov

**Comment by Chinaski1** [comment]
Hello!

Since the information about the connected devices is dynamic, it makes little sense to add the ability to rename devices.

As for deleting the information about the VPN account. We do not plan to add such a feature.
