### ISSUE TITLE
Improve app menu

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardVPNForMac#113]
### Problem Description

There are no items in the app menu, although this is the standard way to interact with macOS apps.

### Proposed Solution

Add items in the app menu.

### Additional Information

https://developer.apple.com/design/human-interface-guidelines/components/system-experiences/the-menu-bar#app-menu

**Comment by Chinaski1** [comment]
Definitely should be added.

**Comment by rakleed** [comment]
@Chinaski1 @Versty the problem has not been fixed in the latest update 2.1.2 (476). Why did you close this issue?
