### ISSUE TITLE
Remove the quit confirmation from the application if VPN is not connected

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardVPNForMac#114]
### Issue Details

- **AdGuard VPN version:**
  - 1.2.3.205
- **VPN mode:**
  - Local VPN
- **Operating system and version:**
  - macOS 12.4
- **Other network-level software:**
  - AdGuard

### Expected Behavior

If I am not connected to the VPN, then when I close the app, the confirmation window does not appear.

### Actual Behavior

If I am not connected to the VPN, then when I close the app, a confirmation window appears.

### Screenshots

<details><summary>Screenshot:</summary>

![Screenshot 2022-06-14 at 01 42 43](https://user-images.githubusercontent.com/19418601/173459859-ed7957b7-cc73-44d1-a88e-45aca2db29ef.png)

</details>

**Comment by Chinaski1** [comment]
Perhaps we won't abandon the confirmation window. But we should definitely change the text of the window, thank you.

**Comment by rakleed** [comment]
@Chinaski1 but why show this window at all if I was not connected to the VPN?

**Comment by Chinaski1** [comment]
We and the developers have consulted a little and came to the conclusion to remove this popup when there is no connection.
