### ISSUE TITLE
Exclusion doesn't work with domain name

### ISSUE THREAD

**Issue by aliafshany** [AdguardTeam/AdGuardVPNForMac#120]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard VPN version:**
  - Version 1.2.3.205 release
- **Operating system and version:**
  - MacOS 11.6.2
- **Other network-level software:**
  - AdGuard

### Expected Behavior

- not excluding sites 
### Actual Behavior

- not excluding sites 

### Additional Information

It won't exclude a domain if you put it on the list unless you enter the IP instead of the domain.
I also recorded the issue so you can see and understand it in a better way

- the site I just tried is geo-locked, so, unfortunately, you cannot test it on your behalf. but this bug is not only specific to this site, you can test it anywhere

https://user-images.githubusercontent.com/40741745/180150876-732c03ef-5b99-4fbd-b015-62644bda2c96.mp4

**Comment by Versty** [comment]
@aliafshany Hi!
Thank you for the video explanation, we tried to reproduce this issue step by step and it seems to work fine on our side. Could you please send the logs from your device to help us troubleshoot? 
Here are the steps you need to follow: 

1. Open AdGuard VPN settings --> General --> Advanced settings --> Logging level --> Record everything;
2. Reproduce the issue and remember the exact time it happened;
3. Open Settings --> General --> Export logs;
4. Send the archive to apple@adguard.com and mention this issue number in the subject.

**Comment by aliafshany** [comment]
@Versty Hello

by 18:36 I added the domain which was **unsuccessful** , then I deleted the Domain name and added the IP which resulted in reaching the site.
every action took within that minute

[adguard_logs_20220722020646.zip](https://github.com/AdguardTeam/AdGuardVPNForMac/files/9168342/adguard_logs_20220722020646.zip)

**Comment by Versty** [comment]
@aliafshany Thank you, logs received and under investigation.

**Comment by Versty** [comment]
@aliafshany By far the best way to resolve the issue is to update to the latest nightly version through this [link](http://agrd.io/mac_vpn_nightly). Please let me know if it helps.

**Comment by aliafshany** [comment]
> @aliafshany By far the best way to resolve the issue is to update to the latest nightly version through this [link](http://agrd.io/mac_vpn_nightly). Please let me know if it helps.

thank you for suggesting that but I just came from that nightly version to this stable one due to a few bugs, which really annoyed me.
but I will give it another chance.

**Comment by aliafshany** [comment]
@Versty 
I just sent another log for the last nightly version with the same process which I did for the stable one. ( like the quoted reply ).

you have to look up 20:59 this time in order to investigate

> @Versty Hello
> 
> by 18:36 I added the domain which was **unsuccessful** , then I deleted the Domain name and added the IP which resulted in reaching the site. every action took within that minute
> 
> just sent the logs

**Comment by aliafshany** [comment]
i just updated to the last nightly **Version 2.0.0.227 nightly**
still the same.

**Comment by Versty** [comment]
@aliafshany Thanks for the second part of the logs. We found the root of the issue and are currently working on a fix.

**Comment by aliafshany** [comment]
@Versty 
that was so fast :)
I appreciate the time and effort you put into this

**Comment by aliafshany** [comment]
hello there
i want to confirm that this issue still persists on the latest nightly, which released just now.
still same results

<img width="912" alt="image" src="https://user-images.githubusercontent.com/40741745/185798518-92d32920-875b-4956-bd9a-ef57a96e390b.png">

**Comment by ngorskikh** [comment]
@aliafshany Hi! Please check again with the latest version: `2.0.0.237 nightly`. There has been a bunch of fixes over the past months for the exclusions, and they currently seem to work for me. If that's not the case for you, we'll need debug logs from you again, sorry!

**Comment by aliafshany** [comment]
@ngorskikh 
yes, i have had that version since the day it got released and again, the issue still persists.

**Comment by sfionov** [comment]
@aliafshany Can you please check if the problem persists on current nightly version? Exclusions should now respect system DNS settings.
