### ISSUE TITLE
reverting  "current location" to the previous place

### ISSUE THREAD

**Issue by aliafshany** [AdguardTeam/AdGuardVPNForMac#121]
**AdGuard VPN:**
- Version 2.0.0.218 nightly

<img width="912" alt="image" src="https://user-images.githubusercontent.com/40741745/180486562-eb7b9f87-95db-4454-b4fe-877b7b5a21c3.png">

It would be great if you could move the current location to where the Arrow is pointed. Like the stable version, I mean.
It's hard to notice it on the right panel.

**Comment by Versty** [comment]
@aliafshany Hi! 
We discussed your feature request with the development team and decided to keep ninja part clean for the next few versions. However, we are planning to try out another solution to maintain the currently connected server visible.
