### ISSUE TITLE
adding a Subscription remaining time

### ISSUE THREAD

**Issue by aliafshany** [AdguardTeam/AdGuardVPNForMac#122]
**AdGuard VPN**
- Version 2.0.0.227 nightly

<img width="912" alt="image" src="https://user-images.githubusercontent.com/40741745/180488254-bf1dc3f1-22f5-4e4b-9fe7-dbdd4f4180bb.png">

it would be nice to add  a Subscription remaining time info on the "Settings >>> Account" section

**Comment by Versty** [comment]
@aliafshany Great idea! 
We will definitely implement this in the next versions!
