### ISSUE TITLE
server load bar

### ISSUE THREAD

**Issue by aliafshany** [AdguardTeam/AdGuardVPNForMac#125]
Hi there

I've using AG VPN for a long time
i think there is a feature missing here.
I always connect to German servers and sometimes my speed drops hugely.
It's because the server loads not from my internet.
I can change the location to somewhere else and solve this issue but idk which server is speedy atm.

if there were such a server load bar at the bottom of each server it would be more convenient to choose one.

**Btw, if you could please make Berlin server more strong. i get fluctuation often in this particular server. Low speed and ping** 

<img width="912" alt="image" src="https://user-images.githubusercontent.com/40741745/182358631-be88b911-eaf5-48dc-b61d-c226570d57d0.png">

- Version 2.0.0.227 nightly

**Comment by Versty** [comment]
@aliafshany Hi! 
We have discussed your suggestion. Locations differ from each other in the amount and capacity of servers, it would be technically difficult to compare load and not useful enough. So we have no plans to implement this feature in the next few versions.
