### ISSUE TITLE
Export logs issue

### ISSUE THREAD

**Issue by aliafshany** [AdguardTeam/AdGuardVPNForMac#127]
Hello there
idk what happened but after a restart, I couldn't export logs. although I have given AG full disk access.
I get this message:
<img width="491" alt="image" src="https://user-images.githubusercontent.com/40741745/182392815-0bb7b9af-e556-4147-a49b-77963c4fd88d.png">

I'm suing 
- mac os big sur 11.6.2
- Version 2.0.0.227 nightly

a video demo:

https://user-images.githubusercontent.com/40741745/182393183-8b2f95db-a770-4ad7-af6c-86c3d05f755e.mp4

**Comment by Versty** [comment]
@aliafshany Hi, thank you for demo! 
Have the logs been exported at the end of the process? If so, how long does it take? 
Also, after restarting the application, does the issue remain?

**Comment by aliafshany** [comment]
@Versty 
no, they have not
I have restarted both the app and the laptop, but no luck

**Comment by Versty** [comment]
@aliafshany 
Tried to reproduce, but the app works fine on my device. 
Would you mind to reinstall the application and check again? 

Follow this steps to delete all existing AdGuard VPN files and than install nightly version again:
1. Quit AdGuard VPN
2. Open Finder and press Shift+Command+G 
3. Remove com.adguard.mac.vpn from **/Library/Application Support/AdGuard Software** directory 
4. Remove com.adguard.mac.vpn.plist from **~/Library/Preferences** directory
5. Open **Keychain Access** and remove com.adguard.mac.vpn from Local Items
6. Remove AdGuard VPN from **Applications**

**Comment by aliafshany** [comment]
@Versty 
yes, I followed the instruction, and now it's working great again.
thank your for your help

**Comment by aliafshany** [comment]
@Versty 
i followed your instruction
unfortunately it didn't work for me.
but I can export Exclusions.
that's weird.
i tried Beta version and release. they are fine
just the latest nightly version.

**Comment by Versty** [comment]
@aliafshany Weird thing.
So correct me if I'm wrong. Previously, the option to export logs was available until you restarted your laptop. 
And now, even after clean installation, this option still doesn't work in the nightly version.

**Comment by aliafshany** [comment]
@Versty 
Absolutely, how I'm certain in that because I emailed you the logs after creating a few difficulties here.
I'm not sure what occurred to cause this.

**Comment by aliafshany** [comment]
idk how but my issue has been solved
it was not for a reboot or reinstallation for sure because i did all of them that time.
btw you may close this issue if you don't have any further questions.

<img width="912" alt="image" src="https://user-images.githubusercontent.com/40741745/183897225-822833f9-ffea-4f91-9571-c9b0b92dba49.png">

**Comment by Versty** [comment]
@aliafshany Alright! Please, keep me informed.
