### ISSUE TITLE
Mail > Internet Accounts could not verify email/password whilst AGVPN was connected

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardVPNForMac#13]
When opening Mail with AdGuard VPN connected, Mail prompted me for one of my Outlook email account password via Internet Accounts.
Each attempt to enter the password (4x) with AdGuard VPN connected was incorrect, once AdGuard VPN was disconnected it worked again.
### Issue Details

- **AdGuard VPN version:**
  - 1.0.0.109 beta
- **VPN mode:**
  - Not specified by app
- **Operating system and version:**
  - macOS 12.0 Beta (21A5248p)
- **Other network-level software:**
  - AdGuard for Mac

### Expected Behavior

Open Apple Mail and Mail fetches Mail without prompting for email account password.
If the password has expired locally, it is expected that entering the correct password works.

### Actual Behavior

With AdGuard VPN connected, Apple Mail prompts for Outlook email password, it states incorrect email/password combo.
When AdGuard VPN is disconnected, all works correctly.

### Screenshots

<details><summary>Screenshot:</summary>

<img width="463" alt="Screen Shot 2021-06-15 at 06 43 37" src="https://user-images.githubusercontent.com/6005161/121957089-4bcdab80-cda5-11eb-9c5c-7920b7234e88.png">
</details>

### Additional Information

This issue is reproducible by:
1. Closing Apple Mail
2. Set AdGuardVPN to connected
3. Open Apple Mail
4. Apple Mail prompts for email password

- This only happens to one of my two Outlook email addresses.
- All AdGuard VPN settings are default.

**Comment by ameshkov** [comment]
What happens if you use Outlook webmail instead of Apple Mail?
Does it depend on which server you use in AG VPN?

**Comment by jslawler** [comment]
It seems this is less related to Apple Mail, and more related to System Preferences > Internet Accounts.



With AdGuardVPN connected (Miami, France, Finland tested) I was able to connect to my email account via Outlook Webmail, and Outlook for macOS.

When opening System Preferences > Internet Accounts and selecting the email account, it immediately prompted me for a password.


On 15 Jun 2021, at 17:20, Andrey Meshkov ***@***.***> wrote:


What happens if you use Outlook webmail instead of Apple Mail?
Does it depend on which server you use in AG VPN?

**Comment by Chinaski1** [comment]
Hello @jslawler 

Sorry for the late reply.
I tried to reproduce the above situation with different emails but not encounter any issues with the login to the mailbox.

Please clarify if the issue is still recurring?

**Comment by Chinaski1** [comment]
Closed due not reply.
Reopen the task if the issue is still reproduced.
