### ISSUE TITLE
Ping button

### ISSUE THREAD

**Issue by aliafshany** [AdguardTeam/AdGuardVPNForMac#131]
Hello

i was curious if you could add a Ping Button on the app to Ping manually on your own.
<img width="912" alt="image" src="https://user-images.githubusercontent.com/40741745/183895450-0578aca6-be13-4885-ac8f-2aa1c961bf80.png">

**Comment by Versty** [comment]
@aliafshany Hi! 
Nightly version ping information updates every 5 minutes. Which may not seem frequent enough for you. 
But in the release and beta version this interval is 2 minutes. 
The feature you suggested may cause a high server load, so we have no plans to implement it in the near future.
