### ISSUE TITLE
Support additional protocols (Ipsec/L2tp/wireguard)

### ISSUE THREAD

**Issue by aliafshany** [AdguardTeam/AdGuardVPNForMac#132]
hello
if you could please add other protocols as well as OVPN.
The main issue i am experiencing right now is that i cannot share my internet as a hotspot on my mac.

in order to share your internet via hotspot, you need to have a Service on Network tab, but AG uses OVPN which doesn't create any so literally, you can not share anything.

<img width="780" alt="image" src="https://user-images.githubusercontent.com/40741745/183897797-12551e2a-7236-491e-891a-e33c6c5b62f5.png">
<img width="637" alt="image" src="https://user-images.githubusercontent.com/40741745/183898204-3dde1517-8930-4337-9947-f8832802dd02.png">

**Comment by Aydinv13** [comment]
We will consider such a request, but I am afraid that it will not be implemented in the near future.
