### ISSUE TITLE
Connection Time Status 

### ISSUE THREAD

**Issue by aliafshany** [AdguardTeam/AdGuardVPNForMac#133]
Hello
Could you add a connection time status?
for example how many hours we stayed connected to AG during this week, or days of the week with the percentage of connection of that day.

so here is the what i want

1- a total number of hours/days of me being connected to AG
2- a status that shows connection time of days of the week to review it weekly.

best

**Comment by Versty** [comment]
@aliafshany Hi! We have some good news for you. 
Work already in progress, the statistics module will be added soon!
