### ISSUE TITLE
AdGuard 2FA page doesn't detect macOS autofill for 2FA, and thinks it should be a username autofill instead

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardVPNForMac#134]
### Issue Details

- **AdGuard VPN version:**
  - 1.2.3
- **VPN mode:**
  - NA
- **Operating system and version:**
  - macOS 12.5.1
- **Other network-level software:**
  - AdGuard DNS

### Expected Behavior

When logging into AdGuard VPN via Apple ID with AdGuard 2FA enabled, it opens to the AdGuard 2FA login page.
macOS should detect this 2FA login  box as a verification box and enter the verification code for the user.

### Actual Behavior

macOS doesn't detect the 2FA login  box as a verification box and tries to enter a username instead.

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/95468948/185241791-e6cfe633-8f30-4db0-b340-67fb93690ac5.png)

![image](https://user-images.githubusercontent.com/95468948/185241826-b279f7c5-a1f2-4efc-93fd-975fcf5030b4.png)

</details>

**Comment by Versty** [comment]
@jslawler Thank you for noticing! 
This issue is not related to VPN for Mac but will be investigated by our web team.
