### ISSUE TITLE
VPN client launch is stucked sometimes

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardVPNForMac#135]
Hello,

sometimes the client can not start properly and stucked:
![image](https://user-images.githubusercontent.com/45385632/185795113-4eb17b2e-4554-4d3b-9fa8-14df94afcdaf.png)

But I can export logs in this time anyway:
_Logs removed  to protect your privacy_

Please take a look!

Thank you.
Best regards.

**Comment by Versty** [comment]
@ammnt Hi! It's not safe for you privacy to publish logs here. 
In order to track this issue in the logs, we need to know the exact time it is occurred.
Could you, please, follow this steps and send extra logs for a further investigation:

1. Open AdGuard VPN settings --> General --> Advanced settings --> Logging level --> **Record everything**;
2. Reproduce the issue and remeber the exact time it happened;
3. Open Settings --> General --> **Export logs**;
4. Send the archive to `apple@adguard.com` and mention this issue number in the subject.

**Comment by ammnt** [comment]
@Versty, it doesn't make sense. The verbose mode of logging has been turned off after OS rebooting🤦🏻‍♂️

**Comment by Versty** [comment]
@ammnt If I understand you correctly, the app can not start properly from time to time, but not every time. 
Therefore, I would recommend you to change the logging level to `Record everything` while it works fine. This setting stays the same all the way after the application or system restart. 
Then wait for the issue to occur and remember the exact time, restart laptop if needed, collect the logs.
Detailed logs from your device are the only way to find the root of this issue and fix it.

**Comment by ammnt** [comment]
> This setting stays the same all the way after the application or system restart.

No. It's not.

**Comment by Versty** [comment]
@ammnt Alright, we have one more way to collect logs. Perhaps, it will be a bit more complicated, but debug logs is necessary to troubleshoot this issue. 

1. Reproduce the issue and remember the exact time it happened;
2. Open **Terminal**;
3. Use this command to collect the logs `log show --style compact --color auto --predicate 'subsystem == "com.adguard.mac.vpn"' --info --debug --last 2d > ./log135.log`;
4. Open **Finder** and use Search option to find `log135.log` file;
5. Send this file to apple@adguard.com and mention this issue number in the subject.

**Comment by ammnt** [comment]
@Versty, the problem is that this only happens when the operating system starts and only when the connection quality is bad.

**Comment by Versty** [comment]
@ammnt It's fine, wait for the system startup completed and then open the Terminal. 
This bug might be difficult to reproduce, so please take your time.

**Comment by ammnt** [comment]
@Versty, I have sent the logs right now - the ticket number is 632475. Thank you.

**Comment by ammnt** [comment]
@Versty, на абсолютно новом макбуке М2 ещё хуже работает:
[stucked_gui.zip](https://github.com/AdguardTeam/AdGuardVPNForMac/files/9463580/stucked_gui.zip)

Только что настроил всё.

**Comment by aliafshany** [comment]
@Versty 

when you try to remove logs from comments please also delete the history.
i can still download the zip file for this comment: https://github.com/AdguardTeam/AdGuardVPNForMac/issues/135#issue-1345498860

<img width="946" alt="image" src="https://user-images.githubusercontent.com/40741745/192092219-3e7855ac-3eac-4d82-b09a-bb767560d763.png">

**Comment by ammnt** [comment]
Looks like fixed. The error is gone after last release. Thank you.
