### ISSUE TITLE
Client does not respond after a page added to exclusions is unable to load

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardVPNForMac#137]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

- **AdGuard VPN version:**
  - 1.2.3.208
- **VPN mode:**
  - General mode
- **Operating system and version:**
  - macOS 12.5.1 (21G83)
- **Other network-level software:**
  - AdGuard for Mac 2.8.1.1147 release (CL-1.9.86, DNS-1.7.22)

### Issue Details

Добавил ряд доменов в список исключений, но VPN-клиент зависает при обращении к ним. Через некоторое время вешая и всю ОС. Логи будут отправлены на почту.

Спасибо.

**Comment by ammnt** [comment]
Отправил только что - номер тикета # 632589.

**Comment by Aydinv13** [comment]
>Отправил только что - номер тикета # 632589.

Логи получили.

**Comment by Versty** [comment]
@ammnt Мы заметили несколько созданных вами сообщений об ошибках связанных с зависаниями. 
Пока мы изучаем логи, советую провести полную переустановку приложения, вероятно она решит сразу все проблемы. 
Вот [Инструкция как удалить все файлы приложения](https://kb.adguard.com/ru/macos/installation). Следуйте шагам из раздела **Продвинутое удаление**, а потом просто скачайте и установите заново. 
Пишите, если все получится!

**Comment by ammnt** [comment]
@Versty, пробовал и в том числе с переустановкой ОС. Нет изменений.

**Comment by ammnt** [comment]
Looks like fixed. The error is gone after last release. Thank you.
