### ISSUE TITLE
Client gets stuck right after the system startup 

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardVPNForMac#138]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

Периодически при старте ОС возникает ошибка старта VPN-клиента. Логи буду отправлены на почту.

- **AdGuard VPN version:**
  - 1.2.3.208
- **VPN mode:**
  - General mode
- **Operating system and version:**
  - macOS 12.5.1 (21G83)
- **Other network-level software:**
  - AdGuard for Mac 2.8.1.1147 release (CL-1.9.86, DNS-1.7.22)

Спасибо.

**Comment by ammnt** [comment]
Логи отправил на почту - тикет # 632733.

**Comment by ammnt** [comment]
@Versty, нет - поведенчески совершенно другая. Но если выяснится, что причина одна, то конечно закрывайте как дубликат🙅🏻‍♂️

**Comment by Versty** [comment]
@ammnt Пожалуйста, поясните подробнее как проявляется ошибка и чем отличается от упомянутой выше. 
Также, для поиска в логах информации относящейся именно к этой проблеме, нам необходимо знать точное время, в которое произошла ошибка.

**Comment by Versty** [comment]
@ammnt Понятно, спасибо за подробности, будем разбираться.
В качестве временного решения проблемы предлагаю отключить в приложении опцию **Запускать AdGuard VPN при входе в систему**.

**Comment by Versty** [comment]
@ammnt Давайте проверим актуальны ли вышеперечисленные проблемы со стартом приложения на Nightly версии. 
Пожалуйста, удалите приложение используя [продвинутое удаление](https://kb.adguard.com/ru/macos/installation), а затем установите [nightly версию](https://agrd.io/mac_vpn_nightly).

**Comment by ammnt** [comment]
@Versty,
1. Эта инструкция для удаления приложения блокировщика, а не VPN;
2. Этот ночник либо не стартует автоматически при запуске ОС, либо крашится при старте ОС;
3. Если добавить его вручную в автозапуск, то падает сразу с таким репортом:
[log.txt](https://github.com/AdguardTeam/AdGuardVPNForMac/files/9471518/log.txt)

**Comment by Versty** [comment]
@ammnt Да, исправляюсь, вот [соответствующая инструкция для vpn](https://adguard-vpn.com/kb/ru/adguard-vpn-for-mac/installation/). 
Если вы установили без удаления файлов, пожалуйста, переустановите с полным удалением. 

Пожалуйста, не выкладывайте логи на гитхабе, они содержат персональные данные и могут быть использованы злоумышленниками. Логи лучше отправлять нам на почту apple@adguard.com с указанием времени и номера проблемы.

**Comment by ammnt** [comment]
@Versty, полное удаление не решает проблемы запуска:
![image](https://user-images.githubusercontent.com/45385632/187968561-d85a2ca6-45b3-4c21-ba4b-0f9f09479719.png)

**Comment by ammnt** [comment]
@Versty, есть новости по проблемам автозапуска VPN-клиента? Если запускать его вручную через некоторое время после запуска ОС, то всё работает исправно😐

**Comment by Versty** [comment]
@ammnt Мы помним о созданных вами баг-репортах и продолжаем исследовать логи на предмет ошибок. 
Как только появится новая информация или решение об исправлении, я сразу же поделюсь этими новостями тут.

**Comment by ammnt** [comment]
Looks like fixed. The error is gone after last release. Thank you.
