### ISSUE TITLE
Unknown error occurred after the system startup

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardVPNForMac#139]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

Периодически при старте ОС возникает ошибка неизвестная ошибка:
![2022-08-28_21-26-13](https://user-images.githubusercontent.com/45385632/187089154-a1ba30bf-1f6a-4227-b551-dfab7fe431ec.png)

Логи буду отправлены на почту.

- **AdGuard VPN version:**
  - 1.2.3.208
- **VPN mode:**
  - General mode
- **Operating system and version:**
  - macOS 12.5.1 (21G83)
- **Other network-level software:**
  - AdGuard for Mac 2.8.1.1147 release (CL-1.9.86, DNS-1.7.22)

Спасибо.

**Comment by ammnt** [comment]
Логи отправлены. Тикет # 633049.

**Comment by ammnt** [comment]
@Versty, на абсолютно новом макбуке М2 ещё хуже работает:
[try_to_recover_m2.zip](https://github.com/AdguardTeam/AdGuardVPNForMac/files/9463594/try_to_recover_m2.zip)

Только что настроил всё.

**Comment by harry-b** [comment]
@ammnt  из логов вижу, что не проходят запросы на обновление proxy credentials:
error: Error occured when retrieving URL content: Error Domain=NSPOSIXErrorDomain Code=41 "Protocol wrong type for socket" UserInfo={_NSURLErr orFailingURLSessionTaskErrorKey=LocalDataTask <67C4314D-581C-4325-96B2-67542659D86A>.<5>, _kCFStreamErrorDomainKey=1, _NSURLErrorRelatedURLSessionTaskErrorKey=(37878 "LocalDataTask <67C4314D-581C-4325-96B2-67542659D86A>.<5>"

Потому и показывается окно о тех. проблемах. Воспроизводится на найтли ?

**Comment by ammnt** [comment]
@harry-b, привет! Да, а есть ночник с расширенным логированием? Я бы собрал больше данных.

**Comment by ammnt** [comment]
Looks like fixed. The error is gone after last release. Thank you.
