### ISSUE TITLE
Click on the exclusion in the list closes the app and prevents it from further launching

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardVPNForMac#140]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

VPN-клиент падает при обращении к списку исключений, который ранее был импортирован после первичной настройке. Логи и видео будут отправлены на почту.

- **AdGuard VPN version:**
  - 1.2.3.208
- **VPN mode:**
  - General mode
- **Operating system and version:**
  - macOS 12.5.1 (21G83)
- **Other network-level software:**
  - AdGuard for Mac 2.8.1.1147 release (CL-1.9.86, DNS-1.7.22)

Спасибо.

**Comment by ammnt** [comment]
Речь идёт о попытке редактирования списка в GUI.

**Comment by ammnt** [comment]
Логи и видео отправлены - тикет # 634182.

**Comment by Versty** [comment]
@ammnt Добрый день! 
Получили логи и видео, спасибо. А также смогли повторить эту проблему на нашем устройстве, будем искать причину такого поведения. 
Попробуйте при повторном запуске приложения подождать минуту, в итоге оно должно запуститься успешно.

**Comment by Versty** [comment]
@ammnt Удаление и повторное добавление проблемного исключения решило проблему у нас на устройстве.
Проверьте у себя, пожалуйста.

**Comment by ammnt** [comment]
@Versty, подтверждаю.

**Comment by Versty** [comment]
@ammnt Отлично! 
Если вдруг проблема вернется, пожалуйста, сообщите здесь и откройте повторно это обсуждение.

**Comment by ammnt** [comment]
@Versty, этот баг будет исправлен в следующих релизах?

**Comment by Versty** [comment]
@ammnt Мы будем наблюдать за поведением вкладки исключений, и, если проблема воспроизведется повторно, выпустим версию с исправлением.
