### ISSUE TITLE
https://www.dazn.com/

### ISSUE THREAD

**Issue by aliafshany** [AdguardTeam/AdGuardVPNForMac#141]
unfortunately, this site won't open with any of the locations on the app.

could you investigate this?

it seems the IP is blocked on that site

<img width="1286" alt="image" src="https://user-images.githubusercontent.com/40741745/188192386-00d91c2d-6fe6-4681-85ed-3d8f4711dc4a.png">

**Comment by Versty** [comment]
@aliafshany Hi! This is a known issue, dazn.com has already been added to our list. Most of the streaming services detect vpn usage and block access. We are currently working on providing streaming services support.

**Comment by aliafshany** [comment]
@Versty 
is it gonna cost extra or current premium users will be able to use that without paying extra?
