### ISSUE TITLE
app crashes on start

### ISSUE THREAD

**Issue by aliafshany** [AdguardTeam/AdGuardVPNForMac#148]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard VPN version:**
  - 2.0.0.231 nightly
>
- **Operating system and version:**
  - macos 11.7
- **Other network-level software:**
  - AdGuard

### Expected Behavior

app crashes when trying to connect

### Screenshots

https://user-images.githubusercontent.com/40741745/192091938-6adc88c0-94ca-4a4f-8bc8-bf8edd2276fc.mp4

### Additional Information

another crash happend at 13:15 when i was connected to a location. it happened suddenly

i sent the logs to this email `apple@adguard.com`

**Comment by aliafshany** [comment]
i sent another video wth logs to the support email.

**Comment by harry-b** [comment]
@aliafshany
Hi. Please check last nightly version (2.0.0.250-nightly and above).

**Comment by aliafshany** [comment]
@harry-b 
i have no issues with the last version.

u may close this issue then
