### ISSUE TITLE
No connection on MCI network

### ISSUE THREAD

**Issue by aliafshany** [AdguardTeam/AdGuardVPNForMac#149]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard VPN version:**
  - Version 2.0.0.231 nightly

- **Operating system and version:**
  - MacOS 11.7
- **Other network-level software:**
  - AdGuard

### Expected Behavior
- you can not connect to any location

### Screenshots

https://user-images.githubusercontent.com/40741745/192247339-52d67783-5c20-45bb-aaab-1ebec832f603.mp4

### Additional Information
ISP's site: mci.ir ( it's geo-locked to Iran's IP )
it's one of the biggest mobile operators in Iran.

p.s.: logs are already sent

**Comment by Versty** [comment]
@aliafshany If the issue still persists and the current version of the app worked well before, this issue is most likely caused by Iranian government restrictions. So we will keep an eye on the situation.

**Comment by aliafshany** [comment]
@Versty 
yes, it was working great before, and it seems it's a new restriction.

thanks btw
