### ISSUE TITLE
Issues with connection in Zoom

### ISSUE THREAD

**Issue by Icewild** [AdguardTeam/AdGuardVPNForMac#15]
If you start meeting in Zoom with AdGuardVPN on it works. But after several seconds (20-30 seconds) i lose ability to hear or see other participants in meeting. However, as they told me, they still can hear me.
If i disconnect AdGuardVPN during meeting, everything starts to work fine.

**Comment by Chinaski1** [comment]
Hello @Icewild 

Can you please tell me this issue is reproduced regardless of the server selected?
Are you using the Zoom desktop or web version?

**Comment by Icewild** [comment]
Hello there!
I got this issue, while was connected to Finland or Germany.
Zoom desktop.

**Comment by Chinaski1** [comment]
Hi @Icewild 

We tried to reproduce your issue but did not encounter any problems with the connection.

Please clarify the issue arises every time when are you join to meeting?
Maybe you use a third-party application that may affect network traffic? This could be anti-virus, Little Snitch or something similar.

Also, I think it's best to check on the latest version of the VPN app [(1.0.0.117 Nightly)](https://adguard-vpn.com/en/beta.html)

**Comment by zzebrum** [comment]
@Icewild any updates? Can you go to AdGuard VPN Settings tab - Advanced settings, switch to record everything logging level, reproduce the issue with Zoom app. 
Logs can be found here: `~/Library/Group\ Containers/TC3Q7MAJXF.com.adguard.mac/Library/Logs/com.adguard.mac.vpn`

Please send log files to devteam@adguard.com

Do not forget to switch back to Record by default logging level.

**Comment by zzebrum** [comment]
reopen if needed
