### ISSUE TITLE
Preload servers to launch faster

### ISSUE THREAD

**Issue by aliafshany** [AdguardTeam/AdGuardVPNForMac#150]
Hi there
I was wondering if this is possible or not.
You can preload all servers so Adguard can launch faster. And _then_ you can use api to get the updates.

this way is much better and faster, especially for Iranians who can not launch it, and AG stays on the welcome screen.

There is a similar feature on shadowsocks' apps like V2rayng, Sagernet, and Matsuri that you can add a subscription link to them and every time a server gets updated, you can manually/automatically update them.

**Comment by Versty** [comment]
@aliafshany Hi! 
This is a known issue related to being stuck on the loading screen when no internet connection is detected. 
Work is already in progress!
