### ISSUE TITLE
Frankfurt works on android but not on the mac

### ISSUE THREAD

**Issue by aliafshany** [AdguardTeam/AdGuardVPNForMac#156]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard VPN version:**
  - Version 2.0.0.237 nightly
- **VPN mode:**
  - Local VPN
- **Operating system and version:**
  - MacOS 11.7
- **Other network-level software:**
  - AdGuard

### Expected Behavior

The only location that currently works in Iran is Frankfurt, but it only can be accessed with an android phone. It can not be connected on Mac. It will get stuck on "Connecting ... "

### Screenshots

Uploading new.mp4…

**Comment by ameshkov** [comment]
There are many servers in Frankfurt, probably you're actually using different ones on Android and Mac.

Quick question: you're on premium account right? Could you please check the diagnostics inside the app, what endpoint domain name does it print there?

**Comment by aliafshany** [comment]
@ameshkov 
yes i have a 5-year premium subscription.

i have blured some info that might be private but i can share unblured one to your telegram account if you want.

![image](https://user-images.githubusercontent.com/40741745/198268192-fd046b07-7fa2-40e1-9107-1c3ad557192c.png)

**Comment by ameshkov** [comment]
And on macOS?

**Comment by aliafshany** [comment]
@ameshkov 
i exported logs and from a file named state.txt i pasted these.
but the thing is why my premium status is false? maybe it's not fully loaded yet?
idk
i have removed some info again.

Current Location: 
    id: ZGVfZnJ
    country: Germany
    city: Frankfurt
    _premium_: false
    ping bonus: 15
    domain name: dtpt-de-fra-05-hlz9yu7e.adguard.io 
    ipv4: 169.150
    ipv6: 2a02:6ea0:

**Comment by aliafshany** [comment]
adguard.io is blocked in iran
that's why i can't connect on macos

maybe you can bypass this restriction by putting some random sites as a bridge in order to get connected. just an idea.
something like NordVPN's login page which are like this : gorhsgsfblnkbnsFSfjs.com

**Comment by ameshkov** [comment]
Oh ignore this, this is a location property and it's always false for Frankfurt.

What bothers me here is that the domain name is `*.adguard.io` on your Mac and this is different from iOS.

**Comment by ameshkov** [comment]
Could you please restart the app and try again?

**Comment by ameshkov** [comment]
Sorry, please do it in 10 minutes, not right now:)

**Comment by ameshkov** [comment]
Sorted out in TG.
