### ISSUE TITLE
Kill Switch broken if AdGuard is disconnected

### ISSUE THREAD

**Issue by alex-osm** [AdguardTeam/AdGuardVPNForMac#163]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard VPN version:**
  - v1.2.3.208
- **VPN mode:**
  - VPN
- **Operating system and version:**
  - MacOS 13.0
- **Other network-level software:**
  - AdGuard

### Expected Behavior

As I understand - Kill Switch feature should block access to the Internet (at least for hosts and apps which are not in the exclusions list) when AdGuard is disconnected or connecting to VPN. I.e. when there is any chance to pass traffic through non secure connection (non VPN).
For example when Wi-Fi connection was not active for some time and AdGuard is reconnecting. This could happen often when Mac wake from sleep.

### Actual Behavior

Kill Switch does not block Internet connection while AdGuard is disconnected or connecting to VPN.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Versty** [comment]
@alex-osm, hi!
Kill-switch feature intended to block internet access when the connection is dropped suddenly, but not while the vpn is intentionally disconnected. 
You can read more about the kill-switch in our [Knowledge Base](https://adguard-vpn.com/kb/general/why-adguard-vpn/#7-kill-switch).
