### ISSUE TITLE
Cineworld is blocked on the UK server

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardVPNForMac#18]
https://ttrp-www.cineworld.co.uk/#/ and https://www.cineworld.co.uk/#/ are blocked when using the UK server. Works fine on other European and USA servers.

![image](https://user-images.githubusercontent.com/15856304/126061775-08c0fe0c-e23d-437e-a24b-5194c9c94547.png)

**Comment by Chinaski1** [comment]
Unfortunately, many popular websites try to block VPN providers or their data centres.
As a temporary solution, customers can use another location to bypass the blocking.
