### ISSUE TITLE
UI Design is horrid

### ISSUE THREAD

**Issue by Htin** [AdguardTeam/AdGuardVPNForMac#182]
### Prerequisites
I am running the latest version
I checked the documentation and found no answer
I checked to make sure that this issue has not already been filed

### Problem Description

UI is very back dated filled with cartoon vectors. Making it look like an unprofessional tool / developers made it. Adguard has a clean more modern approach, corporate identity is missing from the looks of Adguard VPN. Even the logo of Adguard VPN looks very amateur, something you can find with a free logo generator online. Know your audience, people who purchase Adguard products are mostly professional adults. Though you might want to cater to younger audience, there should be more effort to design instead of looking like free vector images from freepik.com.

### Proposed Solution

Take notes from the Adguard APP to redesign Adguard VPN.

**Comment by Aydinv13** [comment]
Thank you for your request regarding the design of the app. We will definitely take it into consideration. 
>Take notes from the Adguard APP to redesign Adguard VPN.

Of course we can, but unfortunately in future major versions. I'm closing this issue for now.
