### ISSUE TITLE
Automatically connect on the system starts is bugged

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardVPNForMac#184]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

Sometimes the application does not automatically connect when the system starts. If you try to connect manually, then we have an infinite "Connecting." Restarting the application solves the problem. The verbose logs will be sent on email.

- **AdGuard VPN version:**
  - 2.0.0.279
- **Operating system and version:**
  - macOS 13.1
- **Other network-level software:**
  - AdGuard 2.9.1.1217 release

**Comment by Aydinv13** [comment]
Thanks, your logs were received. We will check.

**Comment by ammnt** [comment]
@Aydinv13, please pay attention that the context menu is not loaded too:
![2023-01-02_14-55-08](https://user-images.githubusercontent.com/45385632/210228107-191dad97-f738-493c-826f-553724d998e9.png)

Looks like this is UI issue😮‍💨

**Comment by Aydinv13** [comment]
Sorry for a big delay. We seem to have worked out what the problem might be. Will be fixed.

**Comment by ywwact** [comment]
I also had this issue with the latest version, emailed to support@adguard.com already and had not get reply from your side

**Comment by Aydinv13** [comment]
@ywwact 
Sorry for not replying, we will answer as soon as possible.

**Comment by ammnt** [comment]
@Aydinv13, please update this task. I still have this issue with the last build and clear installation.

**Comment by Aydinv13** [comment]
@ammnt 

problem solving in progress.

**Comment by ammnt** [comment]
@Aydinv13, after the last update of adblocker and vpn clients I still have the infinite "Connecting..." behaviour. Please check this video:
https://www.youtube.com/watch?v=Got3cgZvlW4&hd=1
and some logs for you:
[adguard_logs_20230417021820_adblock.zip](https://github.com/AdguardTeam/AdGuardVPNForMac/files/11251190/adguard_logs_20230417021820_adblock.zip)
[adguard_logs_2023041702191_vpn.zip](https://github.com/AdguardTeam/AdGuardVPNForMac/files/11251196/adguard_logs_2023041702191_vpn.zip)

Thank you.

**Comment by Aydinv13** [comment]
@ammnt 

Unfortunately we didn't fix this problem in that update.

**Comment by harry-b** [comment]
Hi @ammnt  Can you check your real connection status please ? I mean check your ip somewhere on 2ip.ru or myip.com. In your logs I see you are really connected to the location - so it looks like this is status displaying issue.

**Comment by ammnt** [comment]
> Hi @ammnt Can you check your real connection status please ? I mean check your ip somewhere on 2ip.ru or myip.com. In your logs I see you are really connected to the location - so it looks like this is status displaying issue.

Nope, the connection has not been established actually:
![2023-05-19_21-34-55](https://github.com/AdguardTeam/AdGuardVPNForMac/assets/45385632/2b6f14d0-6bd5-4d7b-b929-f49c0eddc40f)

The verbose logs was sent to support@adguard.com just now.

**Comment by ammnt** [comment]
@Aydinv13 and @harry-b, it is more clear now about this issue?

**Comment by harry-b** [comment]
Hi @ammnt. Can you check please the latest beta (2.1.0.390 beta)

**Comment by ammnt** [comment]
> Hi @ammnt. Can you check please the latest beta (2.1.0.390 beta)

1. My DNS server is not available now for some reason:
![image](https://github.com/AdguardTeam/AdGuardVPNForMac/assets/45385632/de7fa7b5-2b69-4519-8e9a-278014b5184e)
2. I have a crash on 22:23-22:25 MSK and today morning during auto-start;
3. Autoconnect still not working for me...
4. The logs has been sent yesterday.

**Comment by ammnt** [comment]
@harry-b, the logs has been sent to your email just now. Please take a look.

**Comment by harry-b** [comment]
@ammnt Thank you for reply. By the way - did you send crash reports ? I don't see any crashes for this version.

**Comment by ammnt** [comment]
> @ammnt Thank you for reply. By the way - did you send crash reports ? I don't see any crashes for this version.

Sure. I sent you the crash logs twice. Also with report tool.

**Comment by harry-b** [comment]
@ammnt we have a new nightly (2.1.0.394-nightly). It would be great if you could check all your issues there.

**Comment by harry-b** [comment]
@ammnt You are welcome

**Comment by ammnt** [comment]
@harry-b, I had a crash this morning at 6:02 MSK and sent logs to the email. Please take a look!

**Comment by harry-b** [comment]
@ammnt I don't see any crash report for this version (2.1.0.394 nightly) from you.

**Comment by ammnt** [comment]
> @ammnt I don't see any crash report for this version (2.1.0.394 nightly) from you.

@harry-b, I don't know why you don't see the crash in my logs. Did you checked the verbose logs that was sent to the support email? What do I need to do now?☹️

**Comment by harry-b** [comment]
@ammnt 
if app crashes I need a crash report (not  logs) to figure out the reason. You can send it next time app starts after crash.
<img width="562" alt="Screenshot 2023-06-01 at 10 56 24" src="https://github.com/AdguardTeam/AdGuardVPNForMac/assets/1119809/ca8e4f14-6315-4523-aa3b-31403b365c3f">

**Comment by ammnt** [comment]
@harry-b, hmm. Looks like it's because your sentry blocked. I will sent you the crash logs again tonight🤭

**Comment by ammnt** [comment]
@harry-b, has been few minutes ago:
![2023-06-01_21-45-41](https://github.com/AdguardTeam/AdGuardVPNForMac/assets/45385632/0a3b4470-1c68-4086-a17e-bb79d1956d18)

**Comment by harry-b** [comment]
@ammnt Now I see all your crash reports. Thanks

**Comment by ammnt** [comment]
@harry-b, it works perfect for now😌

**Comment by harry-b** [comment]
@ammnt Good news. I was about to ask you to check the latest nightly build. Thanks

**Comment by ammnt** [comment]
@harry-b, already tested! Build 406 works perfect😏

**Comment by ammnt** [comment]
@harry-b, FYI - the RC build works fine too🫡
