### ISSUE TITLE
MacOS 10.14 not supported, proposing a Wireguard file for older OS

### ISSUE THREAD

**Issue by fsmeurinne** [AdguardTeam/AdGuardVPNForMac#185]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

VPN APP not supported on MacOS 10.14 version 

### Proposed Solution

Wireguard file to use VPN with older OS

### Alternatives Considered

Support older MacOS versions

### Additional Information

Would like to use the new VPN I bought with my MacBookPro, I know is an old version, and I can't upgrade it due to compatibility issues with some Apps I use and because it's a vintage laptop.

**Comment by fsmeurinne** [comment]
Would like to use the new VPN I bought with my MacBookPro, I know is an old version, and I can't upgrade it due to compatibility issues with some Apps I use and because it's a vintage laptop. So I hope a Wireguard file can be downloaded to use VPN on older OS.

**Comment by maxikuzmin** [comment]
@fsmeurinne unfortunately with the latest update to 2.0 the app needs macOS version 10.15 or newer.

**Comment by maxikuzmin** [comment]
@fsmeurinne you can download a previous version [AdGuardVPN-1.2.3.208-release](https://github.com/AdguardTeam/AdGuardVPNForMac/releases/download/v1.2.3.208/AdGuardVPN-1.2.3.208-release.dmg) and use it
