### ISSUE TITLE
Why there is no usable VPN services these days?

### ISSUE THREAD

**Issue by doctorasoce** [AdguardTeam/AdGuardVPNForMac#188]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ yes] I am running the latest version
- [ yes] I checked the documentation and found no answer
- [ yes] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard VPN version:**
  - <v2.0.1.3>
- **VPN mode:**
  - <Local VPN / SOCKS5>
- **Operating system and version:**
  - <MacOS 13.0.1) >
- **Other network-level software:**
  - 

### Expected Behavior

<There must have many usable VPN services after I paid for it!>

### Actual Behavior

<There is no usable VPN for almost 1 week!>

### Screenshots

<details><summary>Screenshot
<img width="793" alt="截屏2023-01-08 23 11 10" src="https://user-images.githubusercontent.com/112327483/211204417-f292ff4a-2ff5-4e98-9ffe-d479711e2f0e.png">
:</summary>

</details>

**Comment by ameshkov** [comment]
Chinese authorities seem to be blocking most of the endpoints at this point.

We're working on it, the situation should improve soon.
