### ISSUE TITLE
Unable to connect to a location

### ISSUE THREAD

**Issue by flanksurvey** [AdguardTeam/AdGuardVPNForMac#189]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ y] I am running the latest version
- [ y] I checked the documentation and found no answer
- [ y] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard VPN version:**
  - 
- **VPN mode:**
  - 
- **Operating system and version:**
  - 
- **Other network-level software:**
  - 

### Expected Behavior

Unable to connect to VPN despite (the "connecting..." status remains endlessly active) :

- both Mac OS and AdGuard VPN up to date
- reinstalled the product 
- restarted Mac OS
- tried different servers
- Other VPNs apps (Windscribe, NordVPN working flawlessly with any kind of protocol). Of course they were disabled during the use of Adguard VPN.
- iCloud private relay disabled
- tried to switch off adguard app
- Fiber optics connection (200mbps download)

### Actual Behavior

Nothing works despite all elements described above.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

_Logs have been deleted for privacy reasons_

### Additional Information

- Works flawlessely on iOS
- Logs attached

**Comment by maxikuzmin** [comment]
@flanksurvey your issue is in progress

**Comment by flanksurvey** [comment]
Hello, have you been able to resolve the issue?

**Comment by maxikuzmin** [comment]
@flanksurvey your issue is in progress. We need a little more time

**Comment by maxikuzmin** [comment]
@flanksurvey to troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

- Open AdGuard VPN settings --> General --> Advanced settings --> Logging level --> Record everything;
- Reproduce the issue and remeber the exact time it happened;
- Open Settings --> General --> Export logs;
- Send the archive to apple@adguard.com and mention this issue number in the subject.

**Comment by flanksurvey** [comment]
No. I have sent logs via email, updated the App and Mac OS, still not working

**Comment by maxikuzmin** [comment]
@flanksurvey I don't see your logs in the mail. Did you email your logs to [apple@adguard.com](mailto:apple@adguard.com)?

**Comment by flanksurvey** [comment]
I have but from a different web address (25 January 2023, 15:20).

**Comment by maxikuzmin** [comment]
@flanksurvey can you upload the logs to google drive and provide access just for us?

**Comment by flanksurvey** [comment]
[com.adguard.mac.vpn.log](https://github.com/AdguardTeam/AdGuardVPNForMac/files/10676813/com.adguard.mac.vpn.log)
[state.txt](https://github.com/AdguardTeam/AdGuardVPNForMac/files/10676814/state.txt)
You can have access directly here I have masked the email address

**Comment by maxikuzmin** [comment]
@flanksurvey thank you! We will check your logs

**Comment by maxikuzmin** [comment]
@flanksurvey judging by your logs, do you also have Kaspersky installed? AdGuard VPN is not compatible with Kaspersky right now, but we are working on it

**Comment by maxikuzmin** [comment]
@flanksurvey unfortunately, the solution to this problem at the moment is to disable Kaspersky.
Perhaps in the future we will be able to solve this problem
