### ISSUE TITLE
Replace default DNS in the network interface

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardVPNForMac#195]
### Issue Details

Hello,

I setup my own DNS server in ad-blocker and VPN client but I still have default DNS servers from VPN client in the network interface settings:
![image](https://user-images.githubusercontent.com/45385632/221400295-af0fff1a-2746-4e98-acdf-491e465c3a9c.png)
this lead to:
![image](https://user-images.githubusercontent.com/45385632/221400306-0a9a03eb-40a0-44f7-89d6-46b41491549b.png)

Looks like they are used for bootstrap anyway. How to change there to my own servers?🤔

Thank you.
Bers

**Comment by sfionov** [comment]
@ammnt AGVPN always set these IPs to network interface. Then, if DNS upstream is selected in Adguard VPN, it intercepts DNS queries and redirects to selected DNS upstream.

Looking up "dns-unfiltered.adguard.com" during every connection is removed in the latest version of VpnLibs, which will be included is the next release.
