### ISSUE TITLE
Launch at login doesn't work correctly on macOS Ventura

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardVPNForMac#197]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.0.3.317

### Environment

```markdown
- OS: 13.2.1
- Other network-level software: AdGuard for Mac adblocker
```

### Issue Details

Launch at login doesn't work after fresh installations, but even this turned on:
![image](https://user-images.githubusercontent.com/45385632/221990166-af34a040-f069-4fb7-bb57-0db3872646d3.png)

Reinstall with advanced removal doesn't help.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

The verbose logs will be sent on demand.

**Comment by ammnt** [comment]
![image](https://user-images.githubusercontent.com/45385632/221991248-1004dfc9-6201-441f-980c-e7495308291f.png)

**Comment by Aydinv13** [comment]
@ammnt Hi there!

To troubleshoot this issue, we need to get the app logs.
Here's what we need you to do:
1. Open AdGuard VPN settings --> General --> Advanced settings --> Logging level --> **Record everything**;
2. Reproduce the issue and remeber the exact time it happened;
3. Open Settings --> General --> **Export logs**;
4. Send the archive to `apple@adguard.com` and mention this issue number in the subject.

**Comment by ammnt** [comment]
@Aydinv13, the logs has been sent just now🫡

**Comment by AcTweeteR** [comment]
Same problem for me runing on mac arm64 with lastest os version

**Comment by TakaiSaisei** [comment]
Same problem, it doesn't work for me for at least two months now.

**Comment by Aydinv13** [comment]
We will figure out what the problem might be and fix it as soon as possible.

**Comment by AcTweeteR** [comment]
Yes, solved for me. But now the app do not open in the background like before

**Comment by ammnt** [comment]
I can confirm. It starts automatically, but now it is not hidden and not automatically connected. Literally for a second, the inscription "Connecting..." appears, but then I have to press the button manually to connect and then hide the application. Can sent the verbose logs to you if you need🫡

**Comment by shark696969** [comment]
Stackautomatical

Pada tanggal Sab, 1 Apr 2023 00.12, ammnt ***@***.***>
menulis:

**Comment by shark696969** [comment]
Star automatic

**Comment by Aydinv13** [comment]
> I can confirm. It starts automatically, but now it is not hidden and not automatically connected. Literally for a second, the inscription "Connecting..." appears, but then I have to press the button manually to connect and then hide the application. Can sent the verbose logs to you if you need🫡

as for the problem, when the program starts maximized we have already created the issue https://github.com/AdguardTeam/AdGuardVPNForMac/issues/203 

@ammnt could you collect the debug logs with auto-connect related problem please?

@TakaiSaisei @AcTweeteR do you also face auto-connect failure now?

Thank you in advance.

**Comment by TakaiSaisei** [comment]
@Aydinv13 no, I have auto-connect working fine with latest update and launch at login enabled.

**Comment by ammnt** [comment]
@Aydinv13, the verbose logs is attached:
[adguard_logs_20230405093556.zip](https://github.com/AdguardTeam/AdGuardVPNForMac/files/11157331/adguard_logs_20230405093556.zip)

![2023-04-05_12-35-12](https://user-images.githubusercontent.com/45385632/230042758-b723c2a1-1a4d-4679-a255-6ef6daf8c73c.png)

**Comment by Aydinv13** [comment]
@ammnt 

Got your logs. We're gonna investigate them. Thank you.

**Comment by Aydinv13** [comment]
@ammnt 

The problem you report is related to https://github.com/AdguardTeam/AdGuardVPNForMac/issues/184. Watch for updates there please. I'm closing current issue as Launch at login bug was fixed.
