### ISSUE TITLE
Support Passkeys

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardVPNForMac#198]
### Proposed solution

_Based on industry standards for account authentication, passkeys are easier to use than passwords and far more secure. Adopt passkeys to give people a simple, secure way to sign in to your apps and websites across platforms — with no passwords required._

[What are Passkeys?](https://developer.apple.com/passkeys/)
[Developer documentation](https://developer.apple.com/documentation/authenticationservices/public-private_key_authentication/supporting_passkeys)

**Comment by Aydinv13** [comment]
There are no plans to implement passkeys for VPN on Mac yet, maybe we will come back to this issue later. Thank you!
