### ISSUE TITLE
Kaspersky Internet Security compatibility

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardVPNForMac#202]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.0.4.331 stable

### Environment

```markdown
- OS: macOS 13.2.1 (22D68) Ventura
- Other network-level software: AdGuard AdBlocker 2.9.2.1234 release, KIS 21.1.0.150f.g.
```

### Issue Details

Hi.

I have installed Kaspersky Internet Security 21.1.0.150f.g. Adblocking works fine, but VPN doesn't want connecting to any servers. I added apps folders to the "Trusted zone" section, but it doesn't help. Any chance to make it work?🙃

I ask because adblocking works fine and use the same network proxy or something like that. The verbose logs will be sent on demand😗

Thank you.

### Expected Behavior

VPN connected with the adblocker and KIS at the same time.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by maxikuzmin** [comment]
@ammnt thank you! We have a recurring problem, we need some time to figure it out

**Comment by maxikuzmin** [comment]
@ammnt  in Kaspersky you cannot add VPN to the list of trusted applications (there is no such option), applications conflict with each other. Unfortunately, it is impossible to fix this from our side.
This will only be possible by adding applications to the trusted list in Kasperksy, if such a feature appears in Kaspersky in the future
