### ISSUE TITLE
Add Touch ID confirmation support for AdGuard VPN updater 

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdGuardVPNForMac#21]
Current double password confirmation kinda butthurts

**Comment by Chinaski1** [comment]
Implemented in the latest nightly version and will be added to Beta/RC soon.

**Comment by Chinaski1** [comment]
I just wanted to clarify a few things.
We fixed the double password request.
But for now, we leave the update confirmation according to the old mechanism (using a password, not via Touch ID)
