### ISSUE TITLE
Add the ability to search a country by ISO 3166-1 alpha-3 codes (e.g. USA, JPN, CHE)

### ISSUE THREAD

**Issue by contribucious** [AdguardTeam/AdGuardVPNForMac#211]
## Issue Details

Hi. As [requested](https://github.com/AdguardTeam/AdGuardVPNExtension/issues/85#issuecomment-1519630931) by the AdGuard team …

↪️ **Please refer to:** https://github.com/AdguardTeam/AdGuardVPNExtension/issues/85

Thanks in advance! 🙂

**Comment by rakleed** [comment]
Please also add country search by `ISO 3166-1 alpha-3` codes (e.g. USA, JPN, CHE).

**Comment by rakleed** [comment]
@zzebrum could you please add `uk` for the United Kingdom?

https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Imperfect_implementations
