### ISSUE TITLE
AdGuard VPN keeps adding AdGuard DNS servers instead of custom 

### ISSUE THREAD

**Issue by TakaiSaisei** [AdguardTeam/AdGuardVPNForMac#214]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.0.4.332 release

### Environment

```markdown
- OS: Ventura 13.3.1
- Other network-level software: AdGuard
```

### Issue Details

1) Set DNS server in AdGuard VPN settings to the custom one (8.8.8.8, 192.168.1.1)
2) Delete all DNS servers in system preferences
3) After restarting AdGuard VPN, DNS list in system preferences does not contain the server I chose in the app, but 94.140.14.140 - the AdGuard one

### Expected Behavior

DNS list contains server chosen in the AdGuard VPN settings, DNS list does not contain any other servers

### Additional Information

This is really important to me - sometimes this DNS is dead (for me, at least), and I spend a whole bunch of time trying to figure out why I don't have internet

**Comment by ameshkov** [comment]
Could you please check if AG DNS is actually used? Visit https://adguard.com/test.html to see if it is.

The thing is that custom DNS works by intercepting all DNS traffic regardless of where it goes and reroute it to the custom servers, therefore it's not obvious from the net settings which one is actually used.

And one more thing. You shouldn't use 192.168.* as a custom DNS server. This is a private IP range which cannot be accessed via VPN.

**Comment by TakaiSaisei** [comment]
> The thing is that custom DNS works by intercepting all DNS traffic regardless of where it goes and reroute it to the custom servers, therefore it's not obvious from the net settings which one is actually used.

Oh, I see. Seems like AG DNS is not actually used. I will close it, thank you.
