### ISSUE TITLE
App freezes or vpn doesn't work

### ISSUE THREAD

**Issue by WoodieDudy** [AdguardTeam/AdGuardVPNForMac#224]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.1.0.407 release (407)

### Environment

```markdown
- OS: macOS Ventura 13.4 (22F66)
- Other network-level software:
wireGuard: off
Tunnelblick: worked fine with it before
```

### Issue Details

Hi, I ran into problems using adguard vpn on macos. Until today, the application was working fine. Today I decided to add the Pycharm app to Exceptions, before I had no apps in Exceptions, only websites. And the adguard vpn app interface started to freeze. I tried restarting it and the mac itself, and reinstalling the app - didn't help. Then I tried to remove all files connected with the application XD ```sudo find . -type f -name "*adguard*" -delete```. To my surprise, the application itself was not deleted and the interface even worked, but the vpn itself stopped connecting (visually everything worked, but not really). After some time the application started to freeze again. I tried again to delete all the files and exec the same command. Now my authorization in the application was deleted and also the list of countries available for connection disappeared (totally). Now even reinstalling it doesn't help to get the countries back.
Next day the interface suddenly worked and VPN too, but not for long. I set up site Exclusions and the VPN stopped working again. I also managed to save the logs

Screen capture: https://drive.google.com/file/d/1B0BSOuvE1ebbF9F_C7TIabS7RtyDssFc

### Expected Behavior

Interface not freezing and vpn works

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by AlexandrPkhm** [comment]
Hi @WoodieDudy!

Unfortunately, we have not been able to reproduce the UI freezing issue related to adding the PyCharm application to exclusions. Could you please try to perform an advanced uninstall of AdGuard VPN using the steps from the [following article](https://adguard-vpn.net/kb/adguard-vpn-for-mac/installation/#advanced-uninstallation) and install the latest stable build available [here](https://github.com/AdguardTeam/AdGuardVPNForMac/releases/download/v2.1.0.407/AdGuardVPN-2.1.0.407-release.dmg). 

Please let us know if the issue persists.

**Comment by WoodieDudy** [comment]
Sorry, I switched my laptop, and cant reproduce the issue any more. Issue can be closed

**Comment by WoodieDudy** [comment]
I changed my mac and installed a AdguardVPN on it. There were no more problems with freezing. 
I also solved the problem of not working VPN. VPN stops working on chosen sites when I turn on the mode "VPN enabled only for the applications selected below". I think this is the wrong behavior, and VPN should also continue to work on the selected sites

**Comment by AlexandrPkhm** [comment]
@WoodieDudy 

We are happy to hear that the performance issues have been resolved. 

Regarding the issue with selective modes of website and app exclusions. Could you please clarify whether the browser you use to view the sites is added to the list of selected applications?

**Comment by WoodieDudy** [comment]
No

**Comment by AlexandrPkhm** [comment]
@WoodieDudy 

Please make sure you add the browser you use to visit the selected sites to the list of selected applications. Otherwise, AdGuard VPN won't tunnel traffic for this particular browser, and you won't be able to use VPN for selected pages in this browser.

**Comment by WoodieDudy** [comment]
I added. Now it works. Thanks
