### ISSUE TITLE
Memory leak on MacOS - using over 60Gb

### ISSUE THREAD

**Issue by hrua** [AdguardTeam/AdGuardVPNForMac#230]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.1.0.407

### Environment

```markdown
- OS: MacOS Ventura 13.4.1 (c)
- Other network-level software: ZScaler 3.9.0.90
```

### Issue Details

Just keep AdGuard running for some time
Then check memory usage and see it being over 60Gb

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by sfionov** [comment]
@hrua Thank you for report! This bug is fixed in 2.1.1 Beta, you may try it you face the problem often.

Original issue: https://github.com/AdguardTeam/VpnLibs/issues/47
