### ISSUE TITLE
Submit AdGuard VPN in App Store

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardVPNForMac#241]
### Issue Details

The AdGuard VPN site is currently being blocked in Russia (this may happen in other countries in the future), so it is difficult for users to download your application.

### Proposed solution

Add the app to the App Store so that more users in Russia can download it: https://developer.apple.com/macos/submit/

**Comment by AlexandrPkhm** [comment]
Hi @rakleed!

Currently, we are planning to publish AdGuard VPN on Mac App Store, but we cannot provide a timeframe for this. As a temporary solution, we recommend using official mirror sites.
