### ISSUE TITLE
Non-solid background in list of servers in dark theme

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardVPNForMac#244]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.1.2 (476)

### Environment

```markdown
- OS: macOS Ventura 13.5.1 (22G90)
- Other network-level software: AdGuard
```

### Issue Details

Not a solid background in the list of servers in a dark theme, but as if striped - now a lighter, now a darker stripe. You need to enable a dark theme in macOS.

### Expected Behavior

Monochrome background in the server list in the dark theme.

### Screenshots

<details><summary>Screenshot:</summary>

![Screenshot 2023-09-04 at 02 25 19](https://github.com/AdguardTeam/AdGuardVPNForMac/assets/19418601/6eeddbd4-687f-4b81-835b-43514d87a6c1)

</details>

**Comment by rakleed** [comment]
@zzebrum without hardware accelerated enabled, the issue is still relevant

**Comment by AlexandrPkhm** [comment]
Hi @rakleed,

The issue you are experiencing is a rendering issue specific to macOS. The design of the application itself is not the source of the problem. In fact, the hardware acceleration option was created to combat visual glitches, including this one. 

Unfortunately, at this time Hardware acceleration is the only solution.
