### ISSUE TITLE
Remove the word `release` from the number of the stable (release) version

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardVPNForMac#250]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.1.2 (476)

### Environment

```markdown
- OS: macOS Ventura 13.5.1 (22G90)
- Other network-level software: AdGuard
```

### Issue Details

No other app for its stable (release) version of the app adds the word `release` to the version number, as this information is meaningless. I understand when you add `beta` or `nightly`, but `release` is definitely not needed.

### Expected Behavior

The stable (release) version of the AdGaurd VPN contains only the version number of numbers without the word `release`.

### Screenshots

<details><summary>Screenshot 1:</summary>

![Screenshot 2023-09-05 at 04 49 14](https://github.com/AdguardTeam/AdGuardVPNForMac/assets/19418601/0ab8367d-2433-40f4-8051-15fb9a06d9f0)

</details>

**Comment by alexx7311** [comment]
@rakleed We added this word recently, and it helps us with our customer support processes. We haven't made any decisions about the AdGuard ad blocker yet, but we will keep the word for VPN for now.

**Comment by rakleed** [comment]
@alexx7311

> We haven't made any decisions about the AdGuard ad blocker yet

The Windows version doesn't have the word `release` in the version number, also you [removed it from the macOS version](https://github.com/AdguardTeam/AdguardForMac/issues/1099) a year ago, and it doesn't seem to have caused any problems.

<details><summary>Screenshot from Windows</summary>

![Screenshot 2023-09-18 at 23 58 53](https://github.com/AdguardTeam/AdGuardVPNForMac/assets/19418601/2da26f71-f904-4f6f-95b2-2c588be8a85b)

</details>

**Comment by rakleed** [comment]
@Aydinv13 @alexx7311 ping
