### ISSUE TITLE
Add optional connection obfuscation

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardVPNForMac#259]
### Issue Details

Nowadays it is often not possible to connect to your servers from Russia.

### Proposed solution

Add optional obfuscation when connecting, for example using V2Ray or Xray or Shadowsocks.

**Comment by joetimmy** [comment]
Yes this needs to be added

**Comment by ameshkov** [comment]
This makes no sense with AdGuard VPN protocol, you can consider it obfuscated by default.

**Comment by rakleed** [comment]
@ameshkov 

> The second approach is "targeted" blocking when they target specific VPN servers by IP address. There's no obfuscation that can help with that, if an IP address is blocked, it is blocked.

So even V2Ray or Xray or Shadowsocks can't solve this problem? Can this only be solved by frequently changing server IP addresses or are there other ways?

**Comment by ameshkov** [comment]
> So even V2Ray or Xray or Shadowsocks can't solve this problem? 

No.

> Can this only be solved by frequently changing server IP addresses or are there other ways?

All these ways boil down to changing IP addresses in the end.
