### ISSUE TITLE
Selective mode causes errors in sites and applications whose traffic doesn't go through VPN

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardVPNForMac#271]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.1.5 (497)

### Environment

```markdown
- OS: macOS 14.0 (23A344)
- Other network-level software: N/A
```

### Issue Details

If I use AdGuard VPN in split tunnel mode and filter, for example, only the WebStorm, VS Code and Grammarly Desktop applications and the *.github.com site, then sometimes my Todoist application says that it works offline, although it is still synchronized with the server, and the stream on Twitch freezes. Although if I disable AdGuard VPN, these problems disappear.

### Expected Behavior

Sites and applications that shouldn't be filtered by AdGuard VPN work correctly.

### Screenshots

<details><summary>Screenshot 1:</summary>

Todoist:

![Screenshot 2023-09-19 at 02 24 31](https://github.com/AdguardTeam/AdGuardVPNForMac/assets/19418601/511bf441-6ed6-4b98-8c45-c66e224ff1bd)

</details>

**Comment by Aydinv13** [comment]
@rakleed hi there!

If I get you right, you are using Selective mode both in Websites and Apps. Unfortunately, no errors in Todoist and freezes on Twitch were reproduced on our side. Could you please collect the debug logs with the latest release and send them to us:

1. Open AdGuard VPN settings --> General --> Advanced settings --> Logging level --> **Record everything**;
2. Reproduce the issue and remeber the exact time it happened;
3. Open Settings --> General --> **Export logs**;
4. Send the archive to `apple@adguard.com` and mention this issue number in the subject.

**Comment by Aydinv13** [comment]
@rakleed any update?

**Comment by rakleed** [comment]
@Aydinv13 sometimes not a single site opens at all, because for some reason you set your own DNS in the connection settings in macOS, although I have Cloudflare DNS selected in AdGuard and AdGuard VPN. Let's start with this.

<details><summary>Screenshots</summary>

![CleanShot 2023-10-31 at 17 55 55](https://github.com/AdguardTeam/AdGuardVPNForMac/assets/19418601/1184d21e-3617-4247-a968-6da19b18a514)

![CleanShot 2023-10-31 at 18 52 45](https://github.com/AdguardTeam/AdGuardVPNForMac/assets/19418601/e9aa566f-5923-4140-9016-a499d0ac8536)

![CleanShot 2023-10-31 at 18 52 58](https://github.com/AdguardTeam/AdGuardVPNForMac/assets/19418601/01377928-59ce-4544-8988-f8baa6e7a118)

</details>

**Comment by Aydinv13** [comment]
>... for some reason you set your own DNS in the connection settings in macOS, although I have Cloudflare DNS selected in AdGuard and AdGuard VPN.

This is expected behaviour, because this is how traffic is intercepted in AdGuard VPN: these addresses in System settings lead to AdGuard VPN, which in turn redirects this traffic to the selected dns.

**Comment by rakleed** [comment]
@Aydinv13 @harry-b why did you put off fixing the problem so much and marked it as priority 3? For every 4-5 launches of macOS, the Internet does not work completely because of this problem.

**Comment by Aydinv13** [comment]
@rakleed we are working on it. Could you grab the debug logs again but using the latest beta version?

**Comment by rakleed** [comment]
At least now you don’t have to force your DNS into the Wi-Fi system settings. I will try to reproduce the problem with the Internet being completely non-functional and send you the logs.

**Comment by rakleed** [comment]
@Aydinv13 I don't know where I should have sent the logs, but I sent them to apple@adguard.com and devteam@adguard.com

The Internet did not work when connecting to AdGuard VPN. When disabled, everything worked correctly

**Comment by marknefedov** [comment]
@Aydinv13 Hi! it looks like I've encountered a similar issue (ticket 892487, wrote a week ago and never heard back). Can you take a look?
