### ISSUE TITLE
Selective mode displays "VPN is on for all websites/apps" when the list is empty

### ISSUE THREAD

**Issue by DumpAndForget** [AdguardTeam/AdGuardVPNForMac#273]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.1.7 release (511)

### Environment

```markdown
- OS: 14.1.1 Sonoma
- Other network-level software: WireGuard, ShadowSocks (shouldn't be related to the matter at hand)
```

### Issue Details

1. Open the AdGuard VPN app
2. Go to Exclusions
3. Select Websites
4. Click on "everywhere" in "VPN is on everywhere", and select Only on selected websites, thus activating Selective mode. Confirm the activation.
<img width="796" alt="image" src="https://github.com/AdguardTeam/AdGuardVPNForMac/assets/145553988/c99f4f96-3b27-439a-bd3d-2f3b256209d5">
5. Leave the list empty, go back to the Exclusions screen.

6. On this screen it says "VPN is on for all websites", even though it's not true at all. With empty list in Selective mode you will have VPN off for all websites, and that is exactly what is happening in reality (I checked).
<img width="800" alt="image" src="https://github.com/AdguardTeam/AdGuardVPNForMac/assets/145553988/5c950c05-9659-49ea-8e00-ca4086e45e40">
7. Do the exact same thing, but now in Apps, and you will get the same result - with empty list in Selective mode on this screen you will have "VPN is on for all apps", again - the reality is opposite.

### Expected Behavior

Even though there is an explicit warning about that behavior on Websites / Apps screen, I still don't see any reason why you should outright misinform on the Exclusions screen.
When there is an entry in the list, it shows the amount of entries.
<img width="796" alt="image" src="https://github.com/AdguardTeam/AdGuardVPNForMac/assets/145553988/eca151b2-6a6f-4a6b-bb4e-ef43d6ae9cf0">
<img width="797" alt="image" src="https://github.com/AdguardTeam/AdGuardVPNForMac/assets/145553988/f7352980-3427-45c4-af2f-8d58d8c3726e">
Perhaps the simple way to do it is to show "VPN is on for 0 selected websites (apps)". Maybe you would prefer a different approach.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Aydinv13** [comment]
@DumpAndForget Hi there!

Thanks for the note, we will fix it.
