### ISSUE TITLE
eats up memory

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardVPNForMac#291]
### AdGuard VPN version

2.2.0 (534)

### Environment

```markdown
- OS: 14.2.1 (23C71)
- Other network-level software:
```

### Issue Details

<img width="449" alt="Screenshot 2023-12-26 at 4 38 03 PM" src="https://github.com/AdguardTeam/AdGuardVPNForMac/assets/154074726/eedbefa2-f0df-46ef-8708-a808d5c9b84f">

**Comment by AlexandrPkhm** [comment]
Hi @kfdsgjskdlfg 

We apologize for the delayed response. Could you try to reproduce this issue on the latest version, which is [AdGuard VPN for Mac 2.2.1](https://github.com/AdguardTeam/AdGuardVPNForMac/releases/tag/v2.2.1.545)? Please let us know the results.
