### ISSUE TITLE
Crash on 101 (nightly)

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdGuardVPNForMac#3]
Steps to reproduce:
- enable "Auto-connect on app launch"
- launch AdGuard VPN (it will try to auto-connect)
- click on "connect"
- AdGuard VPN will be crashing

Logs: 
https://we.tl/t-YUvptK5yY7

I also reported it to the team (ticket number is 508840) because I wasn't able to log in to my old account :)

**Comment by Chinaski1** [comment]
Hello @iDjay 

On Friday we released Nightly 117 which supposedly solved your crash.
Please, update the AdGuard VPN app and check if the issue still reproduced?

Let us know the result.

**Comment by blashman** [comment]
Sorry, where is supposed we can find Nightly 117?

**Comment by ameshkov** [comment]
Here you can find all nightly/beta builds: https://adguard-vpn.com/en/beta.html

**Comment by iDjay** [comment]
seems to be fixed.

**Comment by Chinaski1** [comment]
Great to hear it! :)
