### ISSUE TITLE
Sign in with Google not working: redirect_uri_mismatch

### ISSUE THREAD

**Issue by alekzuz** [AdguardTeam/AdGuardVPNForMac#316]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.2.1.545 release

### Environment

```markdown
- OS: macos 14.0
- Other network-level software:
```

### Issue Details

400: redirect_uri_mismatch
on sign in using Google

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by AlexandrPkhm** [comment]
@alekzuz Hi!

We have tried to reproduce the problem, but were unable to do so. Could you please let us know if this issue persists? And if so, let us know if you use any other network related software besides AdGuard VPN?

**Comment by AlexandrPkhm** [comment]
@alekzuz 

Could you please let us know if there are any news on the issue?
