### ISSUE TITLE
Can't Sign in Adguard VPN

### ISSUE THREAD

**Issue by chumido98** [AdguardTeam/AdGuardVPNForMac#32]
### Issue Details

- **AdGuard VPN version:**
  - Newest version on website (both official and beta)
- **Operating system and version:**
  - MacOS BigSur 11.5.2
- **Other network-level software:**
  - AdGuard (Ad block)

### Screenshots

![CleanShot 2021-08-25 at 21 40 16@2x](https://user-images.githubusercontent.com/61721378/130811523-9d01ddbc-54ed-422e-b955-17b7401e9a48.png)

**Comment by Chinaski1** [comment]
@chumido98 

Hello!
Could you please clarify, is the issue still reproducing?

**Comment by Chinaski1** [comment]
Closed due to no reply.
