### ISSUE TITLE
Can't open any site in Chrome sometimes

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardVPNForMac#334]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.3.2

### Environment

```markdown
- OS: 14.5
- Other network-level software: AdGuard
```

### Which DNS server do you use?

Google DNS

### Issue Details

Steps to reproduce:
1. Enable AdGuard VPN
2. After a few minutes, I can't open any site in Chrome

### Expected Behavior

I can open any site in Chrome

### Actual Behavior

I can't open any site in Chrome

### Additional Information

Logs sent to apple@adguard.com

**Comment by AlexandrPkhm** [comment]
Hi @rakleed 

Unfortunately, we have not been able to reproduce this issue on our end. Could you please try to install the latest nightly version of AdGuard VPN for Mac and check if the problem persists with this version? The latest Nightly is available from the following [link](https://agrd.io/mac_vpn_nightly).

If the issue persists, please record the Nightly application logs for us and send them to [apple@adguard.com](mailto:apple@adguard.com).
