### ISSUE TITLE
GeoIP & TLDs

### ISSUE THREAD

**Issue by aliafshany** [AdguardTeam/AdGuardVPNForMac#335]
### Issue Details

there are so many sites that i need to exclude from AdguardVPN. like certain Geo-Locations.

### Proposed solution

Adding a V2Ray JSON-like feature which enables us to add routing rules like GeoIP: IR or *.ir for specific TLDs.

**Comment by AlexandrPkhm** [comment]
Hi @aliafshany 

This can already be achieved by exporting exclusions via Export exclusions feature and manually editing the list (for example, adding *.ir or other TLDs) and then importing the list back into the app.
