### ISSUE TITLE
Port Exclusion

### ISSUE THREAD

**Issue by aliafshany** [AdguardTeam/AdGuardVPNForMac#337]
### Issue Details

Hello there, would you please try to add a port/port range exclusion feature as well? It would be nice to have a feature like domain exclusions.

### Proposed solution

Adding a port exclusion box next to domains

**Comment by sfionov** [comment]
@aliafshany Port is supported in exclusions, however UI currently does not allow you to enter it :(

As a workaround you may export exclusions, add `IP:port`, and import them

**Comment by aliafshany** [comment]
@sfionov 
So if I need to bypass every connection to a random IP but with the same port, do I need to enter 127.0.0.1:PORT? There is no specific IP for my need, like I need to bypass every connection to 8443.

**Comment by Aydinv13** [comment]
> do I need to enter 127.0.0.1:PORT?

you need to specify an ip address of the domain, not localhost.

Regarding the implementation of port exclusion, this is not planned in the near future, but we will probably look into it later. Thank you for the suggestion.
