### ISSUE TITLE
Setanta Sports blacklisted

### ISSUE THREAD

**Issue by Blender538** [AdguardTeam/AdGuardVPNForMac#347]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.3.2

### Environment

```markdown
- OS: 15.1 Beta (24B5024e)
- Other network-level software:
```

### Which DNS server do you use?

AdGuard DNS

### Issue Details

Steps to reproduce:
1. connect with Ukraine VPN
2. go to https://setantasports.com
3. click on watch now
<img width="1624" alt="Screenshot 2024-08-25 at 11 53 33" src="https://github.com/user-attachments/assets/94be1860-08c1-4cd2-b5d4-d18e5bd3ce31">

### Expected Behavior

Website should be accessible

### Actual Behavior

website recognizes VPN and is blocked

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

same with Moldova server

**Comment by Aydinv13** [comment]
@Blender538 Hi there!

We will most likely include this domain, but not in the near future, we are not currently considering this possibility. Thank you for contacting us.
