### ISSUE TITLE
`Protect from DPI` in AdGuard doesn't work when VPN is enabled

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardVPNForMac#348]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.3.2

### Environment

```markdown
- OS: 14.6.1 (23G93)
- Other network-level software: AdGuard
```

### Which DNS server do you use?

Google DNS

### Issue Details

Steps to reproduce:
1. Enable `Protect from DPI` in Stealth Mode options in AdGuard
2. Enable AdGuard VPN with selected mode for sites and apps, then add Chrome and Safari to app list
3. Try to open https://zona.media or any other blocked site from Russia

### Expected Behavior

Sites are opening.

### Actual Behavior

Sites don't open.

### Additional Information

Logs sent to apple@adguard.com. Related issue: https://github.com/AdguardTeam/AdguardForMac/issues/1469

**Comment by AlexandrPkhm** [comment]
Hi @rakleed 

This is expected behavior and no changes are planned at this time.
