### ISSUE TITLE
Adguard VPN For Mac crashed

### ISSUE THREAD

**Issue by ArturD94** [AdguardTeam/AdGuardVPNForMac#363]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.4.1 release [705]

### Environment

```markdown
- OS: Catalina 10.15.2
- iMac 27" Late 2015
```

### Which DNS server do you use?

Default

### Issue Details

At one moment there was a connection error. 
After that, it never connected again. I tried reinstalling it, but the installation does not complete.
I've tried different versions and it's always the same error

### Expected Behavior

No crash

### Actual Behavior

Crash

### Screenshots

<img width="1112" alt="Снимок экрана 2024-11-16 в 23 14 45" src="https://github.com/user-attachments/assets/e8deffcf-0237-4159-8dcf-67a510dae460">
<img width="577" alt="Снимок экрана 2024-11-16 в 23 14 43" src="https://github.com/user-attachments/assets/0858d02c-c6bb-47c5-97b5-5cf34b5c7953">

### Additional Information

[Log.docx](https://github.com/user-attachments/files/17787837/Log.docx)

**Comment by Aydinv13** [comment]
@ArturD94 Hi there!

Where did you get the installer from?

**Comment by Aydinv13** [comment]
Any news? Also, you can try to install the latest [Nightly](https://agrd.io/mac_vpn_nightly) build.

**Comment by ArturD94** [comment]
I installed ver. 2.31 and it work. -- 
 Защищено с помощью Tuta Mail: 
 https://tuta.com/free-email


26 нояб. 2024 г., 13:49 От ***@***.***:

**Comment by Aydinv13** [comment]
Anyway, we will be glad if you have a chance to try installing the latest builds. I am closing the task for now, but it can be reopened
