### ISSUE TITLE
AdGuard VPN full disk access necessary?

### ISSUE THREAD

**Issue by sergerosenthaler** [AdguardTeam/AdGuardVPNForMac#38]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard VPN version:**
  - 1.0.0.136
- **VPN mode:**
  - 
- **Operating system and version:**
  - macOS 11.6 (20G165)
- **Other network-level software:**
  - Sophos Home Premium 10.1.4

### Expected Behavior

AdGuard VPN adds himself to the list of applications that need full disk access without any information.

### Actual Behavior

AdGuard VPN should inform the user about this and if necessary the user should be informed to activate full disk access.

### Screenshots

<details><summary>Screenshot:</summary>

<img width="763" alt="image" src="https://user-images.githubusercontent.com/25068100/134336839-c53878e9-1d74-430e-ad7e-2291c06f307f.png">

</details>

**Comment by Chinaski1** [comment]
Hello there!

Sorry for the late reply.

When you trying to save the files to the `~/Desktop/` and `~/Downloads`folders (think logs in our case), the system asks the user for permission.
If the user grants this permission, the checkbox appears and the program can write files to these directories.

**Comment by Chinaski1** [comment]
I close this task.

Reopen it if you still have questions.
