### ISSUE TITLE
Sign in with Apple option missing

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdGuardVPNForMac#4]
You can't use "sign in with Apple" with the current 109 beta build. 
The option is not visible while launching the app.
<img width="912" alt="Bildschirmfoto 2021-05-20 um 16 52 20" src="https://user-images.githubusercontent.com/83946731/119000943-d92b0500-b98b-11eb-91d9-b2ff035fd1a6.png">

**Comment by Chinaski1** [comment]
Hello there!

We will definitely add authorisation via Apple account in the near future.

**Comment by iDjay** [comment]
added in 117 nightly, but it takes around 30 seconds to sign in.
