### ISSUE TITLE
Feature request: let us choose an alternative dns server

### ISSUE THREAD

**Issue by stramargio** [AdguardTeam/AdGuardVPNForMac#74]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

It's not possible to choose an alternative DNS server (ipv6 or ipv4 address).

### Proposed Solution

Add a feature (like on iOS app) to let the user specify a DNS server address (ipv4 or ipv6).

### Alternatives Considered

Using AdGuard in conjunction with AdGuardVPN is not a solution. It would be great to choose a DNS server from the AdGuardVPN app.

### Notes

Thanks in advance for your time and for your great service!

**Comment by ameshkov** [comment]
Already possible in the beta version:
![image](https://user-images.githubusercontent.com/5947035/147823289-c37ae5db-ac6c-4b38-a088-b8a8350e1e94.png)

**Comment by stramargio** [comment]
Can't find this setting in the beta ver.
<img width="912" alt="Screenshot 2021-12-31 at 14 07 25" src="https://user-images.githubusercontent.com/1104037/147825035-fa0c452b-8de3-4236-b21a-13b7304ae22a.png">

Am I watching in the wrong place?

**Comment by stramargio** [comment]
Nightly build is ok.
Thanks!
