### ISSUE TITLE
Change DNS server from Adguard DNS with no filtering

### ISSUE THREAD

**Issue by ArthurHandke** [AdguardTeam/AdGuardVPNForMac#75]
- AdGuard VPN for macOS uses Adguard DNS without filtering by default, but I would like users to be able to change it to AdGuard DNS with filtering, for example.

- Currently, there is no option to change the DNS server.

- For some reason, the DNS server option is available in AdGuard for macOS.

- AdGuard VPN for Android allows users to change the DNS server.

- In AdGuard VPN for Windows, the DNS server is set to Adguard DNS server with filtering, which is an inconsistent policy.

**Comment by ameshkov** [comment]
There's a way to change the DNS server in AdGuard VPN beta:
![image](https://user-images.githubusercontent.com/5947035/148768718-d2184e3f-b9ee-4ae0-86f2-289d1347208d.png)
