### ISSUE TITLE
Cannot access sites using a specific rental server when selecting Japan Server.

### ISSUE THREAD

**Issue by ArthurHandke** [AdguardTeam/AdGuardVPNForMac#77]
When I use AdGuard VPN's Japan server, I cannot access sites using Xserver, the largest rental server in Japan, due to "ERR_CONNECTION_REFUSED".

https://www.xserver.ne.jp/
(Japanese only)

The following is an example of sites using the Xserver from the official website.

Kyoto Seika University
https://award.kyoto-seika.ac.jp/

Saga Prefectural Tourism Federation
https://www.asobo-saga.jp/

Since I can access the sites by changing the server to South Korea or by using Cloudflare WARP, it seems that the VPN itself is not prohibited.

Also, there does not seem to be any benefit in excluding certain users from a website designed to introduce the school and the tourism.

So, I think there is a problem on the Japan server that AdGuard VPN is using.

I'm currently using AdGuard VPN (Version 1.1.0.167 release), but the above problem has existed since the beginning of the service, even with the current Beta and Nightly versions, and with any browser, including Chrome (macOS, Android) and Safari (macOS).

**Comment by Chinaski1** [comment]
I jumped to conclusions a little bit.

Websites of Kyoto Seika University
https://award.kyoto-seika.ac.jp/

Saga Prefectural Tourism Federation
https://www.asobo-saga.jp/

Really not available, passed the information on to the developers
