### ISSUE TITLE
Не работают исключения и невозможно добавить их по IP

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardVPNForMac#80]
Здравствуйте,

не уверен, что при добавлении домена `nalog.ru` в исключения оно вообще работает, но при попытке добавить IP-адреса `81.176.70.2` и `81.176.235.2` этого домена в исключения появляется ошибка:
![image](https://user-images.githubusercontent.com/45385632/156134321-b915fd57-1b79-44ca-ab1f-4dc761b7e82d.png)

Также при добавлении домена `гибдд.рф` исключение не работает. Только при добавлении его IP-адресов `82.202.189.118` и `82.202.189.119`. В punycode его добавить также невозможно ни в верхнем ни в нижнем регистрах:
![image](https://user-images.githubusercontent.com/45385632/156135849-5c10a45c-67f1-4904-8819-78044ac94520.png)

Расширенные логи в приложении:
[adguard_logs_20220301084515.zip](https://github.com/AdguardTeam/AdGuardVPNForMac/files/8160136/adguard_logs_20220301084515.zip)

Спасибо.

**Comment by Chinaski1** [comment]
Добрый день!

Данная ситуация должна быть исправлена в Nightly версии приложения.
Вы не могли бы, пожалуйста, обновиться и проверить будет ли повторяться проблема?

Ссылка на скачивание [Nightly](https://agrd.io/mac_vpn_nightly).

**Comment by ammnt** [comment]
@Chinaski1, смогу проверить на релизе. Отпишусь.

**Comment by ammnt** [comment]
Исправлено. Спасибо.
