### ISSUE TITLE
VPN app stops responding after connecting to the server

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardVPNForMac#85]
Здравствуйте,

после сегодняшнего обновления. Тезисно:
1. Приложение больше не подключается автоматически при запуске ОС;
2. Опция "Подключить" через контекстное меню в строке меню не работает;
3. После этого при подключении в самом приложении к серверу бесконечно висит "Соединение..." и кнопка "Отключить" не отвечает. Выбор других серверов тоже не работает;
4. Если сразу открыть приложение (не нажимая кнопку "Подключить" через контекстное меню в строке меню не работает) и нажать зеленую кнопку "Подключить", то подключается. Но автоподключение при перезагрузке ОС всё равно не работает;
5. Дергание ползунков автоподключения в настройках программы проблему не решает. Выбор другого сервера тоже.

Расширенные логи в приложении тут:
https://disk.yandex.ru/d/WiuqMcByOzvysg
https://disk.yandex.ru/d/frO_7IOObTy75w

Спасибо.

**Comment by harry-b** [comment]
Добрый день. 
Не могли бы вы уточнить - меняется ли статус в контекстном меню и в главном окне, при подключении через контекстное меню. Если есть возможность - прикрепите видео.

**Comment by ammnt** [comment]
@harry-b, статус в контекстном меню и в главном окне меняется при подключении через контекстное меню, если до этого приложение не крашилось. Если оно уже крашнулось после запуска ОС, то начинаются проблемы в работе контекстного меню - через него не подключается.

Я думаю, что начать нужно с проблемы краша при запуске ОС, потому что пользоваться сейчас невозможно. Дайте, пожалуйста, ссылку на предыдущую стабильную версию.

**Comment by ammnt** [comment]
@harry-b, вот здесь записал видео, когда подключение не работает и функционал не отвечает после попытки подключения через контекстное меню:
https://www.youtube.com/watch?v=_5crB2ce-rQ&hd=1

Если бы я сразу открыл приложение и нажал зеленую кнопку "Подключить", то всё заработало бы отлично.

**Comment by ammnt** [comment]
@harry-b, вот здесь записал краш с самого старта ОС + отправку нескольких репортов с логами:
https://www.youtube.com/watch?v=2bAgzelh33M&hd=1

В конце уже приложение окончательно перестало отвечать и повесило мне всю систему.

**Comment by ammnt** [comment]
Вот здесь расширенные логи для пункта 3 (бесконечное соединение, кнопка отключения и выбор серверов не реагируют, сильно грузит CPU) - только перезапуск приложения помогает:
[adguard_logs_20220320081434.zip](https://github.com/AdguardTeam/AdGuardVPNForMac/files/8312117/adguard_logs_20220320081434.zip)

Спасибо.

**Comment by Chinaski1** [comment]
Вот ссылка на версию [1.1.0.167](https://uploads.adguard.com/Chinaskiejfbe.dmg)

**Comment by ammnt** [comment]
> Вот ссылка на версию [1.1.0.167](https://uploads.adguard.com/Chinaskiejfbe.dmg)

Спасибо вам огромное!🥹

**Comment by ammnt** [comment]
@harry-b, удалось что-то понять из предоставленной информации?

**Comment by harry-b** [comment]
@ammnt С падениями уже разобрались, в ближайшее время выпустим patch и nightly сборку
Спасибо за содействие

**Comment by ammnt** [comment]
@harry-b, поймал краш после патча. Отправил логи. Указал ящик contact@ammnt.app.

**Comment by harry-b** [comment]
@ammnt так это уже другая проблема. Спасибо за репорт - разбираемся

**Comment by harry-b** [comment]
@ammnt мы можем связаться по telegram/skype/... ?
