### ISSUE TITLE
Can't connect to the Severs when using the latest version of AdGuard VPN for Mac

### ISSUE THREAD

**Issue by XYK953651094** [AdguardTeam/AdGuardVPNForMac#86]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details
When I use the older version of AdGuard VPN for Mac, it works well, but when I update the AdGuard VPN for Mac to the latest version, it can't work, please fix the bug.

- **AdGuard VPN version:**
  - v1.2.0.184 release 
- **VPN mode:**
  - Local VPN 
- **Operating system and version:**
  - MacOS 12.3 
- **Other network-level software:**
  - AdGuard 2.7.0.1094 release (CL-1.8.276, DNS-1.6.72) 

### Expected Behavior
<img width="339" alt="截屏2022-03-20 17 45 38" src="https://user-images.githubusercontent.com/28004442/159156867-943588f7-1e45-48e4-a0f3-8f9228718452.png">

### Actual Behavior
<img width="344" alt="截屏2022-03-20 17 47 23" src="https://user-images.githubusercontent.com/28004442/159156875-9d808972-6f0a-4a8b-8ed4-6e3eb8feeb7f.png">

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by ameshkov** [comment]
@XYK953651094 could you please export AdGuard log and send it to `devteam@adguard.com`?

**Comment by XYK953651094** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by ameshkov** [comment]
Received the logs, thank you!

**Comment by ameshkov** [comment]
@XYK953651094 it seems "INFO-level" log is not enough to troubleshoot the issue, we need more:(

Here's what we need you to do:

1. Settings -> General -> Advanced settings
2. Switch the logging level to "Record everything"
3. Reproduce the issue
4. Settings -> General -> Export logs

Send the archive to `devteam@adguard.com`. We'll also need to know what was the time when the issue was reproduced.

**Comment by ammnt** [comment]
I have the same issue when Killswitch is enabled. Looks similar. I also will try to reproduce it and sent you the verbose logs.

**Comment by XYK953651094** [comment]
附件将于2022年4月20日过期
I found that i can’t send the email through QQ Mail, so i resend it through iCloud Mail again.
I exported the logs according to the steps. This problem occurs when the app is first started, I have tried many times, sometimes it keeps showing "Checking...", but sometimes it can return to normal after a while.
点按以下载
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAegdv63uakxZkLl_C5Tb67zNdttFAacXlBB_A9cfsW7r44U9_ZFBkhsj%2F%24%7Bf%7D%3Fo%3DArJToAwmzgGUFHh1dDkT3O_AnhTh__EJs3BrUF_7_-tS%26v%3D1%26x%3D3%26a%3DCAogBil7c2HtqvTGFEulIsrosqP3_XbvxMzTZR_jR-fFDrESehCOg4Dl-i8YjpP7uIQwIgEAKgkC6AMA_2HObvhSBM1220VaBEGSGyNqJxwoM9v-YHjV6kqyTTBrvmn9Aw9p8YCEmTf2FQTxtoViMfVyTupAdHInMlfk14unXtf6y86E49Ed0VmrO6zuiKLJQOuJqPl4wUhIFfm8b99o%26e%3D1650460641%26fl%3D%26r%3D0DB9E9E0-E1FB-4BA4-93D9-4A9A82DAAE2B-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3D7E4FFC1D-4FD3-47C2-A909-34B3083E51A7%26p%3D207%26s%3DaKJFE_ejGIgdKfxYIyt94Qt5i5k&uk=7517jLrjJacidtyF2b-4Mg&f=adguard_logs_20220321032400.zip&sz=16400267>adguard_logs_20220321032400.zip
16.4 MB
点按以下载
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAaZl2AQ7EZPrLm6uOsTNMAU2QYaAAcwjw68nqT8JP3ecfB4GorCupUES%2F%24%7Bf%7D%3Fo%3DApH39ICo-XchiGvIZeP-H3yTENS_dhjWzi4TL8Kdt7rA%26v%3D1%26x%3D3%26a%3DCAogYQh5rf629MVAiLIu46yFSt7_pNYFfvqSSP3jUihbTcwSehCY_f_k-i8YmI37uIQwIgEAKgkC6AMA_yMg79FSBDZBhoBaBK6lQRJqJ6aw-Td7GJCe1waQ4DlvrmK4qcyxdWzkrIovnoRxXaom5a9Yeu0Cw3In6LhTDom5lizVMqs7L-cn6xCjwHSmMdQLaSw0CD3pzmBYeuPNM571%26e%3D1650460640%26fl%3D%26r%3DD2A43789-651C-4BB7-8621-C7E2CBBB2F9D-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3D7E4FFC1D-4FD3-47C2-A909-34B3083E51A7%26p%3D207%26s%3DhFmLFU_n9EfbOEQfokuapZhYABY&uk=cn-hm01HLnkT_SL9mmDjxQ&f=adguard_logs_20220321033834.zip&sz=16476476>adguard_logs_20220321033834.zip
16.5 MB

**Comment by ammnt** [comment]
@ameshkov, reproduced! Here it is:
https://www.youtube.com/watch?v=Nbg4-5-_Dxw&hd=1

The logs from the video:
[adguard_logs_20220321021910.zip](https://github.com/AdguardTeam/AdGuardVPNForMac/files/8316220/adguard_logs_20220321021910.zip)
[adguard_logs_20220321022049.zip](https://github.com/AdguardTeam/AdGuardVPNForMac/files/8316221/adguard_logs_20220321022049.zip)
[adguard_logs_20220321022210.zip](https://github.com/AdguardTeam/AdGuardVPNForMac/files/8316223/adguard_logs_20220321022210.zip)
[adguard_logs_20220321022301.zip](https://github.com/AdguardTeam/AdGuardVPNForMac/files/8316224/adguard_logs_20220321022301.zip)

Please take a look😋

Thank you.

**Comment by ammnt** [comment]
@ameshkov, с этим удалось разобраться? Периодически возникает до сих пор. Спасибо.

**Comment by harry-b** [comment]
@ammnt с этой проблемой еще разбираемся

**Comment by ammnt** [comment]
@harry-b, напишите, если что-то потребуется с моей стороны - займусь в выходные...

**Comment by harry-b** [comment]
@ammnt 
Не получается повторить эту проблему у себя.
Вы не могли бы прислать конфигурацию adguard'а. По видео видно что у вас он запущен. 
Пункт меню "Export logs and system info".

**Comment by harry-b** [comment]
@ammnt Получется воспроизвести эту проблему только на VPN, без запуска adguard

**Comment by ammnt** [comment]
@harry-b, готово:
https://www.youtube.com/watch?v=LXsaugusR3s&hd=1

Логи из видео:
[adguard_logs_20220325014856.zip](https://github.com/AdguardTeam/AdGuardVPNForMac/files/8351065/adguard_logs_20220325014856.zip)
[adguard_logs_20220325014917.zip](https://github.com/AdguardTeam/AdGuardVPNForMac/files/8351066/adguard_logs_20220325014917.zip)
[adguard_logs_20220325015016.zip](https://github.com/AdguardTeam/AdGuardVPNForMac/files/8351067/adguard_logs_20220325015016.zip)
[adguard_logs_20220325015022.zip](https://github.com/AdguardTeam/AdGuardVPNForMac/files/8351068/adguard_logs_20220325015022.zip)

В некоторых случаях подключается к последнему серверу при нажатии зеленой кнопки "Подключить" даже если все серверы "оффлайн". Если так и не получается воспроизвести, то:
1. Включите автоподключение при запуске.
2. Включите killswitch.
3. Запустите приложение и подключитесь к любому серверу. Подождите.
4. Выйдите из приложения через CMD+Q. Подождите.
5. Запустите приложение. Либо оно подключится, либо крашнется (пока что), либо все серверы будут оффлайн.
6. Повторяйте п. 5 до получения желаемого результата🤨

Спасибо.

**Comment by harry-b** [comment]
@ammnt большое спасибо ! Это нам очень поможет. Разбираемся

**Comment by ammnt** [comment]
@harry-b, traceroute когда VPN выключен, сеть работает, а серверы онлайн:

```
❯ traceroute api.adguard.io
traceroute: Warning: api.adguard.io has multiple addresses; using 172.67.208.217
traceroute to api.adguard.io (172.67.208.217), 64 hops max, 52 byte packets
 1  10.0.0.1 (10.0.0.1)  2.414 ms  1.785 ms  1.517 ms
 2  10.80.0.3 (10.80.0.3)  55.210 ms  4.174 ms  3.962 ms
 3  * * *
 4  * * *
 5  87.226.221.70 (87.226.221.70)  5.617 ms  4.725 ms  4.968 ms
 6  188.254.25.75 (188.254.25.75)  5.042 ms
    188.254.25.77 (188.254.25.77)  4.941 ms
    188.254.25.75 (188.254.25.75)  5.079 ms
 7  217.161.68.34 (217.161.68.34)  42.537 ms  42.410 ms  43.081 ms
 8  * * *
 9  ae4-ucr1.czs.cw.net (195.2.10.233)  68.718 ms  67.517 ms  66.701 ms
10  ae8-ucr1.pra.cw.net (195.2.18.250)  66.185 ms  65.586 ms  65.943 ms
11  141.101.94.30 (141.101.94.30)  70.043 ms  67.956 ms  68.001 ms
12  172.67.208.217 (172.67.208.217)  65.569 ms  65.802 ms  65.612 ms

❯ ping api.adguard.io
PING api.adguard.io (172.67.208.217): 56 data bytes
64 bytes from 172.67.208.217: icmp_seq=0 ttl=54 time=66.667 ms
64 bytes from 172.67.208.217: icmp_seq=1 ttl=54 time=66.975 ms
64 bytes from 172.67.208.217: icmp_seq=2 ttl=54 time=67.017 ms
64 bytes from 172.67.208.217: icmp_seq=3 ttl=54 time=65.763 ms
^C
--- api.adguard.io ping statistics ---
4 packets transmitted, 4 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 65.763/66.606/67.017/0.505 ms
```

Вот traceroute когда приложение запущено, серверы оффлайн, но подключение ещё не производилось:
```
❯ traceroute api.adguard.io
traceroute: Warning: api.adguard.io has multiple addresses; using 104.21.91.24
traceroute to api.adguard.io (104.21.91.24), 64 hops max, 52 byte packets
 1  10.0.0.1 (10.0.0.1)  4.168 ms  1.786 ms  1.711 ms
 2  10.80.0.3 (10.80.0.3)  4.369 ms  4.189 ms  4.082 ms
 3  * 192.168.126.212 (192.168.126.212)  9.821 ms  4.476 ms
 4  77.37.250.223 (77.37.250.223)  4.598 ms  4.555 ms  4.754 ms
 5  87.226.221.170 (87.226.221.170)  5.679 ms  9.195 ms  8.486 ms
 6  188.128.126.247 (188.128.126.247)  4.975 ms
    188.254.25.77 (188.254.25.77)  4.692 ms
    188.128.126.247 (188.128.126.247)  4.874 ms
 7  217.161.68.34 (217.161.68.34)  43.152 ms  42.191 ms  42.421 ms
 8  217.161.68.33 (217.161.68.33)  40.750 ms  40.935 ms  40.776 ms
 9  ae4-pcr1.aet.cw.net (195.2.16.98)  48.586 ms  50.304 ms  48.442 ms
10  141.101.65.48 (141.101.65.48)  49.686 ms  51.761 ms  51.076 ms
11  104.21.91.24 (104.21.91.24)  49.337 ms  49.899 ms  48.762 ms
```

Во traceroute после нажатия зеленой кнопки "Подключить" и зависания "Соединение...":

```
❯ traceroute api.adguard.io
traceroute: Warning: api.adguard.io has multiple addresses; using 104.21.91.24
traceroute to api.adguard.io (104.21.91.24), 64 hops max, 52 byte packets
 1  10.0.0.1 (10.0.0.1)  2.312 ms  1.735 ms  1.578 ms
 2  10.80.0.3 (10.80.0.3)  4.033 ms  4.113 ms  3.979 ms
 3  * 192.168.126.212 (192.168.126.212)  4.572 ms  4.247 ms
 4  77.37.250.223 (77.37.250.223)  4.444 ms  4.955 ms  5.096 ms
 5  87.226.221.170 (87.226.221.170)  5.530 ms *  11.172 ms
 6  188.254.25.77 (188.254.25.77)  6.778 ms
    188.128.126.247 (188.128.126.247)  5.903 ms
    188.254.25.77 (188.254.25.77)  7.664 ms
 7  217.161.68.34 (217.161.68.34)  47.085 ms  51.017 ms  54.899 ms
 8  * * *
 9  ae4-pcr1.aet.cw.net (195.2.16.98)  63.721 ms  55.557 ms  52.154 ms
10  141.101.65.48 (141.101.65.48)  89.659 ms  90.436 ms  56.960 ms
11  104.21.91.24 (104.21.91.24)  65.333 ms  48.624 ms  49.868 ms
```

Вот скриншот:
https://disk.yandex.ru/i/AaVCEGtUQd9mLw

Спасибо.

**Comment by ammnt** [comment]
@harry-b, два наблюдения:
1. Может ли быть так, что killswitch блокирует доступ к вашему собственному бэкэнду или мешает отрезолвит его домен?
2. Может ли быть так, что killswitch мешает вообще любому резолвингу, если задан пользовательский DNS в приложении AdGuard или AdGuard VPN?

**Comment by harry-b** [comment]
@ammnt По-идее такого быть не должно, но есть несколько вопросов:
1) получается воспроизвести эту с проблему выключенным killswitch ?
2) на default dns
3) только на VPN без adguard блокировщика ?

Спасибо

**Comment by ammnt** [comment]
@harry-b, вот я только что выключил приложение AdGuard и включил дефолтный DNS в приложении VPN. Теперь у меня вообще чуть ли не в 100 % случаев при запуске показывает, что серверы оффлайн. Сеть есть (mtr для разнообразия):
https://disk.yandex.ru/i/O4I9yDqsnD9tqw

**Comment by harry-b** [comment]
Если так часто воспроизводится - не могли бы снять отладочные логи с VPN:
1) запустить vpn (без авто подключения)
2) включить отладочные логи (record everything) - опция сбрасываются после перезапуска приложения
3) воспроизвести проблему

Логов много, но не нашел именно отладочных логов от VPN

**Comment by ammnt** [comment]
@harry-b, ну сейчас не в 100 % случаев конечно, но расширенные логи собрал:
https://www.youtube.com/watch?v=5Yn0guogRYs&hd=1

[adguard_logs_20220328040428.zip](https://github.com/AdguardTeam/AdGuardVPNForMac/files/8364516/adguard_logs_20220328040428.zip)
[adguard_logs_20220328040532.zip](https://github.com/AdguardTeam/AdGuardVPNForMac/files/8364517/adguard_logs_20220328040532.zip)
[adguard_logs_20220328040658.zip](https://github.com/AdguardTeam/AdGuardVPNForMac/files/8364518/adguard_logs_20220328040658.zip)
[adguard_logs_20220328040819.zip](https://github.com/AdguardTeam/AdGuardVPNForMac/files/8364519/adguard_logs_20220328040819.zip)

Трассировка с видео:

```
❯ traceroute api.adguard.io
traceroute: Warning: api.adguard.io has multiple addresses; using 104.21.91.24
traceroute to api.adguard.io (104.21.91.24), 64 hops max, 52 byte packets
 1  10.0.0.1 (10.0.0.1)  3.815 ms  1.955 ms  1.728 ms
 2  10.80.0.3 (10.80.0.3)  4.092 ms  4.323 ms  4.398 ms
 3  192.168.126.212 (192.168.126.212)  4.309 ms  4.717 ms  4.406 ms
 4  77.37.250.223 (77.37.250.223)  4.553 ms  4.611 ms  4.673 ms
 5  87.226.221.170 (87.226.221.170)  8.667 ms  5.429 ms  5.473 ms
 6  188.254.25.75 (188.254.25.75)  4.826 ms
    188.254.25.77 (188.254.25.77)  4.934 ms
    188.254.25.75 (188.254.25.75)  5.407 ms
 7  217.161.68.34 (217.161.68.34)  41.936 ms  49.982 ms  43.036 ms
 8  217.161.68.33 (217.161.68.33)  58.034 ms  57.734 ms *
 9  ae4-pcr1.aet.cw.net (195.2.16.98)  70.132 ms  68.053 ms  67.018 ms
10  141.101.65.48 (141.101.65.48)  72.057 ms  63.753 ms  63.918 ms
11  104.21.91.24 (104.21.91.24)  67.140 ms  67.302 ms  66.720 ms
```

```
❯ traceroute api.adguard.io
traceroute: Warning: api.adguard.io has multiple addresses; using 104.21.91.24
traceroute to api.adguard.io (104.21.91.24), 64 hops max, 52 byte packets
 1  10.0.0.1 (10.0.0.1)  3.521 ms  1.715 ms  1.525 ms
 2  10.80.0.3 (10.80.0.3)  4.480 ms  4.056 ms  4.007 ms
 3  * 192.168.126.212 (192.168.126.212)  6.181 ms  4.302 ms
 4  77.37.250.223 (77.37.250.223)  4.425 ms  4.601 ms  4.384 ms
 5  * 87.226.221.170 (87.226.221.170)  7.597 ms  12.616 ms
 6  188.254.25.75 (188.254.25.75)  4.817 ms
    188.254.25.77 (188.254.25.77)  4.779 ms
    188.254.25.75 (188.254.25.75)  4.723 ms
 7  217.161.68.34 (217.161.68.34)  42.488 ms  42.177 ms  42.181 ms
 8  * * *
 9  ae4-pcr1.aet.cw.net (195.2.16.98)  71.760 ms  73.944 ms  69.091 ms
10  141.101.65.48 (141.101.65.48)  68.692 ms  69.026 ms  69.019 ms
11  104.21.91.24 (104.21.91.24)  63.921 ms  64.024 ms  62.651 ms
```

```
❯ traceroute api.adguard.io
traceroute: Warning: api.adguard.io has multiple addresses; using 188.114.97.17
traceroute to api.adguard.io (188.114.97.17), 64 hops max, 52 byte packets
 1  * * *
 2  * * *
 3  * * *
 4  * * *
 5  * * *
 6  * * *
 7  * *^C

❯ traceroute api.adguard.io
traceroute: Warning: api.adguard.io has multiple addresses; using 188.114.97.17
traceroute to api.adguard.io (188.114.97.17), 64 hops max, 52 byte packets
 1  * * *
^C
```

```
❯ traceroute api.adguard.io
traceroute: Warning: api.adguard.io has multiple addresses; using 104.21.91.24
traceroute to api.adguard.io (104.21.91.24), 64 hops max, 52 byte packets
 1  10.0.0.1 (10.0.0.1)  2.134 ms  1.685 ms  1.561 ms
 2  10.80.0.3 (10.80.0.3)  4.211 ms  4.248 ms  4.465 ms
 3  * 192.168.126.212 (192.168.126.212)  6.143 ms  4.507 ms
 4  * * *
 5  87.226.221.170 (87.226.221.170)  6.894 ms * *
 6  188.254.25.77 (188.254.25.77)  7.268 ms
    188.254.25.75 (188.254.25.75)  5.000 ms
    188.254.25.77 (188.254.25.77)  4.965 ms
 7  217.161.68.34 (217.161.68.34)  42.191 ms  42.383 ms  42.294 ms
 8  217.161.68.33 (217.161.68.33)  53.079 ms  53.763 ms  59.813 ms
 9  ae4-pcr1.aet.cw.net (195.2.16.98)  61.352 ms  61.008 ms  60.958 ms
10  141.101.65.48 (141.101.65.48)  79.798 ms  73.599 ms  67.965 ms
11  104.21.91.24 (104.21.91.24)  62.418 ms  63.468 ms  61.880 ms
```

P.S.: надеюсь мне дадут когда-нибудь за этот арт-хаус какую-нибудь статуэтку🏆

Спасибо.

**Comment by harry-b** [comment]
Я обязательно проголосую за награду в этой номинации :)
PS
Попробуем разобраться

**Comment by harry-b** [comment]
@XYK953651094 @ammnt  I hope we have fixed this issue. Please try the latest nightly build (1.2.2.198) or wait a few days when the release version will be ready.

**Comment by XYK953651094** [comment]
@harry-b Yes, thanks for your works, I can connect to the server now , but there are still some problems in app's UI. Here it is.
 
<img width="803" alt="截屏2022-04-07 16 30 01" src="https://user-images.githubusercontent.com/28004442/162155987-b82f9cad-be94-4368-9588-c8ac924b9bcf.png">

**Comment by harry-b** [comment]
@XYK953651094 could you please attach debug logs

**Comment by XYK953651094** [comment]
@harry-b 
When I start the app, it can connect to the servers,but shows "checking..." in the server list. But when I switch the logging level to "Record everything", it can show the delay of the server correctly.

Here is the debug logs.
[adguard_logs_20220411023411.zip](https://github.com/AdguardTeam/AdGuardVPNForMac/files/8460625/adguard_logs_20220411023411.zip)

**Comment by Stillness-2** [comment]
@XYK953651094 issue with "checking..." moved to https://github.com/AdguardTeam/VpnLibs/issues/22

**Comment by XYK953651094** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by xyk953651094** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
