### ISSUE TITLE
AdGuard VPN can connect to a server whose status is "Offline"

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdGuardVPNForMac#87]
It seems that the application sometimes gets the server status incorrectly

[Screenshot of the issue](https://uploads.adguard.com/Chinaski59jt1.png)

**Comment by ammnt** [comment]
@Chinaski1, I think this is same:
https://github.com/AdguardTeam/AdGuardVPNForMac/issues/79
https://github.com/AdguardTeam/AdGuardVPNForMac/issues/86
