### ISSUE TITLE
VPN IP Blacklisted

### ISSUE THREAD

**Issue by n00d1e5** [AdguardTeam/AdGuardVPNForMac#89]
I do not if here is the proper place for this issue.

Your VPN servers' IP are currently in the blacklist of several service providers.
- Couldflare -> [flyertalk](https://www.flyertalk.com) | Access denied by Couldflare
- Some Mail provider (forgot the name) -> The mail is blocked by the receiver's mail provider, and my e-mail address goes to their SPAM list

I understood that you do not keep log on your side so as to analyse the behaviour, but that do impact the normal usage...

**Comment by Chinaski1** [comment]
Hello!

Could you please clarify which locations we are talking about?
I would be grateful if you could list them.

**Comment by n00d1e5** [comment]
I did not test all servers, here is a list.
Blocked by Cloudflare: France, Germany (all), Luxembourg, Austria, Belgium, US(NYC, Miami, Chicago), Switzerland
OK: Irland
