### ISSUE TITLE
VPN client will fail or re-connects twice each time the system starts

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardVPNForMac#98]
Hello,

VPN client will fail or re-connects twice each time the system starts, if the AdGuard for Mac is running in parallel:

![image](https://user-images.githubusercontent.com/45385632/161772964-5872fbbe-cb93-4d78-ba65-6715e5c7cff8.png)

The verbose logs right after fail:
[adguard_logs_20220404034806.zip](https://github.com/AdguardTeam/AdGuardVPNForMac/files/8418869/adguard_logs_20220404034806.zip)
[adguard_logs_20220404033438.zip](https://github.com/AdguardTeam/AdGuardVPNForMac/files/8418870/adguard_logs_20220404033438.zip)

The verbose logs right after double re-connect:
[adguard_logs_20220404035016.zip](https://github.com/AdguardTeam/AdGuardVPNForMac/files/8418879/adguard_logs_20220404035016.zip)

Thank you!
Best regards 😋

**Comment by maxikuzmin** [comment]
Good afternoon! Thank you, this problem will be solved in version 1.3

**Comment by ammnt** [comment]
@harry-b, FYI - я проверил сегодня ещё раз и двойное переподключение всё ещё есть. Но ошибки на скриншоте всё же нет после последнего релиза🫡
